/* Gemaakt met Codex. SRA-inhoud met het dashboardpatroon van CAFA2. */
(function(){
 'use strict';
 const D=window.SRAExamData, $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const KEY='sra-exams-v1'; let store={},storageError=false,ctx;
 try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');for(const e of D.exams){const a=raw[e.id];if(a&&typeof a==='object'){store[e.id]={answers:{},marked:{},completed:typeof a.completed==='string'?a.completed:null};for(const q of e.questions){if(typeof a.answers?.[q.number]==='string')store[e.id].answers[q.number]=a.answers[q.number].slice(0,30000);if(a.marked?.[q.number]===true)store[e.id].marked[q.number]=true;}}}}catch(e){storageError=true;}
 function save(){if(storageError)return false;try{localStorage.setItem(KEY,JSON.stringify(store));return true;}catch(e){storageError=true;return false;}}
 const attempt=e=>store[e.id]||(store[e.id]={answers:{},marked:{},completed:null});
 const answered=e=>e.questions.filter(q=>attempt(e).answers[q.number]?.trim()).length;
 const analysedExams=D.exams.filter(e=>!e.duplicateOf);
 const points=e=>e.questions.reduce((sum,q)=>sum+q.points,0);
 const sections=e=>e.sections||[{id:'1',number:1,title:'Steekproeven',points:35,firstQuestion:1,lastQuestion:e.cut,description:e.descriptions[0]},{id:'2',number:2,title:'Regressie',points:65,firstQuestion:e.cut+1,lastQuestion:e.questions.length,description:e.descriptions[1]}];
 const sectionTitle=s=>s.title.replace(/^Opgave\s+\d+\s*[·:]\s*/i,'');
 const sectionQuestions=(e,s)=>e.questions.filter(q=>q.number>=s.firstQuestion&&q.number<=s.lastQuestion);
 const sectionFor=(e,q)=>sections(e).find(s=>q.number>=s.firstQuestion&&q.number<=s.lastQuestion);
 const questionLabel=(e,q)=>e.questions.some(item=>item.originalNumber&&item.originalNumber!==item.number)?'Opgave '+sectionFor(e,q).number+', vraag '+(q.originalNumber||q.number):'Vraag '+q.number;
 const monthYear=e=>new Date(Number(e.id.slice(0,4)),Number(e.id.slice(4,6))-1,1).toLocaleDateString('nl-NL',{month:'long',year:'numeric'});
 const link=(e,part='welkom')=>'#tentamen/'+e.id+'/'+part;
 const pdf=(e,kind='opgaven')=>'bronnen/tentamens/'+e.id+'/'+kind+'.pdf';
 const button=(text,url,primary=false)=>`<a class="study-btn${primary?' primary':''}" href="${url}">${text}</a>`;
 const crumb=title=>ctx.breadcrumb(title,{label:'Tentamens oefenen',href:'#tentamen'});
 function table(rows,headers=['Toetsnaam','Code','Beschikbaar','Deadline','Duur','']){return `<div class="sra-exam-table-wrap"><table class="study-table sra-exam-table"><thead><tr>${headers.map(h=>`<th scope="col">${h||'<span class="sr-only">Actie</span>'}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td colspan="${headers.length}">Geen toetsen</td></tr>`}</tbody></table></div>`;}
 function dashboard(completed=false){
  let rows=[];
  if(!completed){
   rows.push(`<tr><td><a href="#tentamen/mc">SRA oefenvragen</a></td><td data-label="Code">SRA-MC</td><td data-label="Beschikbaar">Altijd beschikbaar</td><td data-label="Deadline">Geen deadline</td><td data-label="Duur">Geen tijdslimiet</td><td>${button('Toets starten','#tentamen/mc',true)}</td></tr>`);
   for(const e of [...D.exams].reverse())rows.push(`<tr><td><a href="${link(e)}">${esc(e.title)}</a><small>${e.onlyAnswers?'Alleen antwoordmodel beschikbaar':`${e.questions.length} open vragen · ${sections(e).length} opgaven · ${points(e)} punten`}${answered(e)?` · ${answered(e)} uitwerkingen bewaard`:''}</small></td><td data-label="Code">${e.id}</td><td data-label="Beschikbaar">Nu beschikbaar</td><td data-label="Deadline">Geen deadline</td><td data-label="Duur">${e.duration?e.duration+' min (bron)':'Niet vermeld'}</td><td>${button(e.onlyAnswers?'Uitwerking':answered(e)?'Toets hervatten':'Toets starten',link(e),true)}</td></tr>`);
  }else for(const e of [...D.exams].reverse())if(attempt(e).completed)rows.push(`<tr><td><a href="${link(e,'resultaat')}">${esc(e.title)}</a></td><td data-label="Code">${e.id}</td><td data-label="Afgerond">${new Date(attempt(e).completed).toLocaleDateString('nl-NL')}</td><td data-label="Beantwoord">${answered(e)} / ${e.questions.length}</td><td data-label="Resultaat">Zelf nakijken</td><td>${button('Weergeven',link(e,'resultaat'),true)}</td></tr>`);
  if(completed)for(const t of window.SRAMC.completed())rows.unshift(`<tr><td><a href="#tentamen/mc/${t.id}/resultaat">SRA oefenvragen · ${esc(t.title)}</a></td><td data-label="Code">SRA-MC</td><td data-label="Afgerond">Onderwerp voltooid</td><td data-label="Beantwoord">${t.done} / ${t.total}</td><td data-label="Resultaat">${t.correct} / ${t.total} goed</td><td>${button('Weergeven','#tentamen/mc/'+t.id+'/resultaat',true)}</td></tr>`);
  $('#main').innerHTML=`${ctx.pageHead('Dashboard')}<div class="study-dashboard sra-exam-dashboard">${ctx.breadcrumb(completed?'Voltooid':'Aankomend')}<label class="sra-exam-view"><span class="sr-only">Toetsen weergeven</span><select id="exam-view"><option value="available">Aankomend</option><option value="completed" ${completed?'selected':''}>Voltooid</option></select></label><section class="sra-exam-section"><h2>${completed?'Voltooide toetsen':'Vandaag'}</h2>${table(rows,completed?['Toetsnaam','Code','Afgerond','Beantwoord','Resultaat','']:undefined)}</section>${!completed?'<section class="sra-exam-section"><h2>Volgende 30 dagen</h2><p class="sra-exam-empty">Geen toetsen</p></section>':''}<section class="sra-analysis-entry"><div><h2>Hoe ziet een SRA-tentamen eruit?</h2><p>Analyse van ${analysedExams.length} inhoudelijk verschillende tentamens: opbouw per opgave, vraagtypen, terugkerende onderwerpen en voorbereiding.</p></div>${button('Bekijk de tentamenanalyse','#tentamen/analyse')}</section><section class="sra-exam-source-section"><h2>Hulpmiddelen</h2><div class="sra-exam-resources">${ctx.sourceLink('formules',1,'Formuleblad')}${ctx.sourceLink('tabellen',1,'Tabellenbundel')}</div></section><footer class="sra-exam-help"><p>Oefenomgeving. De MC-reeks bevat ${window.SRAMCData?.topics.reduce((sum,t)=>sum+t.questions.length,0)||0} eigen oefenvragen, verdeeld over onderwerpen, van makkelijk naar moeilijk; de gedateerde tentamens bevatten de originele open vragen. Je werkt in eigen tempo, zonder aftelklok. Antwoorden blijven op dit apparaat. Open vragen kijk je zelf na.</p><div class="actions"><button class="study-btn" id="exam-backup">Back-up uitwerkingen</button>${button('MC-voortgang','#tentamen/mc/resultaten')}${button('Hoofdpagina','#home')}</div><p id="exam-backup-status" role="status"></p></footer></div>`;
  $('#exam-view').onchange=e=>{location.hash=e.target.value==='completed'?'tentamen/voltooid':'tentamen';};
  $('#exam-backup').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,exams:store},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='SRA-tentamenuitwerkingen.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#exam-backup-status').textContent='Back-up bevat je open uitwerkingen. De MC-voortgang exporteer je via MC-voortgang.';};
 }
 function welcome(e){$('#main').innerHTML=`${ctx.pageHead(e.title)}<div class="study-dashboard">${crumb('Welkom')}<section class="sra-exam-welcome"><h2>${e.onlyAnswers?'Alleen de uitwerking beschikbaar':'Welkom bij het tentamen'}</h2><p>${e.onlyAnswers?'Van dit tentamen ontbreekt het oorspronkelijke vragenbestand. Je kunt het officiële antwoordmodel bestuderen. We presenteren dit niet als een volledig beschikbaar oefententamen.':'Werk de originele vragen in volgorde uit. De bronpagina’s behouden alle tabellen, formules en grafieken. Via de paginakeuze lees je ook de casus en de figuren op andere pagina’s.'}</p><dl class="sra-exam-details"><div><dt>Vragen</dt><dd>${e.questions.length}</dd></div>${sections(e).map(s=>`<div><dt>Opgave ${s.number}</dt><dd>${esc(sectionTitle(s))} · ${s.points} punten</dd></div>`).join('')}<div><dt>Werkwijze</dt><dd>Eigen tempo · zelf nakijken</dd></div></dl>${e.duration?`<p>Op het oorspronkelijke voorblad staat ${e.duration} minuten. In deze oefenomgeving loopt geen aftelklok.</p>`:''}<div class="actions">${button(e.onlyAnswers?'Antwoordmodel openen':answered(e)?'Verder met uitwerken':'Begin met vraag 1',link(e,e.onlyAnswers?'bron':String(e.questions.find(q=>!attempt(e).answers[q.number]?.trim())?.number||1)),true)}${button('Bekijk de analyse van dit tentamen','#tentamen/analyse/'+e.id)}<a class="study-btn" href="${pdf(e,e.onlyAnswers?'uitwerking':'opgaven')}" target="_blank" rel="noopener">Originele PDF ↗</a></div></section></div>`;}
 function viewer(e,kind,page){const pages=e.documents[kind],max=kind==='opgaven'?e.questionPages:pages.length;return `<div class="sra-document-controls"><label>Bronpagina <select id="source-page">${pages.slice(0,max).map((_,i)=>`<option value="${i+1}" ${page===i+1?'selected':''}>${i+1} / ${max}</option>`).join('')}</select></label><button class="study-btn small" id="source-previous" ${page===1?'disabled':''} aria-label="Vorige bronpagina">←</button><button class="study-btn small" id="source-next" ${page===max?'disabled':''} aria-label="Volgende bronpagina">→</button><a class="study-btn small" id="source-zoom" href="${pages[page-1]}" target="_blank" rel="noopener">Vergroten ↗</a></div><div class="sra-original-page"><img id="source-image" src="${pages[page-1]}" alt="Originele ${kind}, ${e.title}, pagina ${page}. De tekstversie staat onder deze afbeelding."><p id="source-missing" hidden>Deze bronpagina ontbreekt. Open het originele PDF-bestand hieronder.</p></div><details class="sra-source-text"><summary>Tekstversie van deze bronpagina</summary><p>Bij formules, grafieken en tabellen is de originele pagina leidend.</p><pre id="source-text">${esc((kind==='opgaven'?e.pageText:e.answerText)[page-1])}</pre></details>`;}
 function bindViewer(e,kind){const sel=$('#source-page'),pages=e.documents[kind],text=kind==='opgaven'?e.pageText:e.answerText;const update=()=>{const n=Number(sel.value);$('#source-image').src=pages[n-1];$('#source-image').alt=`Originele ${kind}, ${e.title}, pagina ${n}. De tekstversie staat onder deze afbeelding.`;$('#source-text').textContent=text[n-1];$('#source-zoom').href=pages[n-1];$('#source-previous').disabled=n===1;$('#source-next').disabled=n===sel.options.length;$('#source-missing').hidden=true;};sel.onchange=update;$('#source-previous').onclick=()=>{sel.value=Number(sel.value)-1;update();};$('#source-next').onclick=()=>{sel.value=Number(sel.value)+1;update();};$('#source-image').onerror=()=>{$('#source-missing').hidden=false;};}
 function runner(e,n){
  const q=e.questions.find(q=>q.number===n);if(!q){welcome(e);return;}const a=attempt(e),section=sectionFor(e,q),label=questionLabel(e,q);
  $('#main').innerHTML=`${ctx.pageHead(e.title)}<div class="sra-exam-runner">${crumb(label)}<article class="sra-exam-paper"><header class="sra-runner-head"><div class="sra-question-id"><span>${q.originalNumber||n}</span><span>Opgave ${section.number} · ${esc(sectionTitle(section))}</span></div><div>POSITIE <strong>${n}</strong> / ${e.questions.length}</div><label><input type="checkbox" id="exam-mark" data-note="exam-mark" ${a.marked[n]?'checked':''}> Markeren</label></header><div class="sra-exam-work"><section class="sra-exam-document" aria-label="Originele tentamenopgave"><h2>${label} <span>(${q.points} ${q.points===1?'punt':'punten'})</span></h2><p class="sra-document-hint">Lees ${label.toLowerCase()} op deze bronpagina. Casus of figuur nodig? Blader door de oorspronkelijke pagina’s.</p>${viewer(e,'opgaven',q.page)}</section><section class="sra-exam-answer"><h2><label for="exam-answer">Mijn antwoord</label></h2><p>Gegevens, methode, berekening en conclusie.</p><textarea id="exam-answer" data-note="exam-answer" maxlength="30000" placeholder="Werk ${label.toLowerCase()} hier uit…">${esc(a.answers[n]||'')}</textarea><p id="exam-save-status" role="status">${storageError?'Opslag niet beschikbaar. Download een back-up vóór je afsluit.':'Je uitwerking wordt tijdens het typen bewaard.'}</p><details id="exam-solution"><summary>Antwoordmodel bij ${label.toLowerCase()}</summary><p>Vergelijk je eigen uitwerking met ${label.toLowerCase()} op de officiële uitwerking. Open antwoorden krijgen geen automatisch cijfer.</p><a href="${pdf(e,'uitwerking')}#page=${q.solutionPage}" target="_blank" rel="noopener">Officiële uitwerking als PDF ↗</a><a href="${e.documents.uitwerking[q.solutionPage-1]}" target="_blank" rel="noopener"><img src="${e.documents.uitwerking[q.solutionPage-1]}" alt="Antwoordmodel ${e.title}, pagina ${q.solutionPage}" loading="lazy"></a><p>Loopt het antwoord door? Lees de volgende pagina in de PDF.</p></details></section></div><nav class="sra-exam-footer" aria-label="Tentamennavigatie"><div>${n>1?button('Vorige',link(e,String(n-1))):'<button class="study-btn" disabled>Vorige</button>'}<button class="study-btn" id="exam-overview">Overzicht</button></div><span id="exam-count">${answered(e)} / ${e.questions.length} beantwoord</span><div>${button('Afronden',link(e,'afronden'))}${n<e.questions.length?button('Volgende',link(e,String(n+1)),true):button('Naar afronden',link(e,'afronden'),true)}</div></nav></article></div>`;
  bindViewer(e,'opgaven');
  $('#exam-answer').oninput=ev=>{a.answers[n]=ev.target.value;const ok=save();$('#exam-save-status').textContent=ok?'Uitwerking bewaard op dit apparaat.':'Opslag niet beschikbaar. Houd deze pagina open en download een back-up via het dashboard.';$('#exam-count').textContent=`${answered(e)} / ${e.questions.length} beantwoord`;};
  $('#exam-mark').onchange=ev=>{a.marked[n]=ev.target.checked;save();};
  $('#exam-overview').onclick=()=>{const dialog=$('#question-overview');$('#question-overview-title').textContent='Vragenoverzicht';$('#question-overview-content').innerHTML=sections(e).map(s=>`<section><h3>Opgave ${s.number} · ${esc(sectionTitle(s))}</h3><ol class="sra-exam-overview">${sectionQuestions(e,s).map(q=>`<li><a href="${link(e,String(q.number))}" ${q.number===n?'aria-current="step"':''}><strong>${q.originalNumber||q.number}</strong><span>${questionLabel(e,q)} · ${q.points} ${q.points===1?'punt':'punten'}</span><span>${a.answers[q.number]?.trim()?'Beantwoord':'Niet beantwoord'}${a.marked[q.number]?' · Gemarkeerd':''}</span></a></li>`).join('')}</ol></section>`).join('');dialog.querySelectorAll('a[href]').forEach(a=>a.addEventListener('click',()=>dialog.close()));dialog.showModal();};
 }
 function finish(e,review=false){const a=attempt(e);$('#main').innerHTML=`${ctx.pageHead(review?'Resultaten':'Tentamen afronden')}<div class="study-dashboard">${crumb(e.title)}<section class="sra-exam-welcome"><h2>${esc(e.title)}</h2><p><strong>${answered(e)} van ${e.questions.length} vragen uitgewerkt.</strong> Dit is het aantal opgeslagen antwoorden, geen score. Vergelijk je berekeningen en redeneringen met het officiële antwoordmodel.</p>${review?'<p>Deze toets staat onder Voltooid. Je kunt je uitwerkingen blijven lezen en verbeteren.</p>':'<p>Ook onbeantwoorde vragen blijven bereikbaar wanneer je de oefenpoging afrondt.</p>'}<div class="actions">${!review?'<button class="study-btn primary" id="exam-finish">Oefenpoging afronden</button>':''}${button('Terug naar vraag 1',link(e,'1'))}<a class="study-btn" href="${pdf(e,'uitwerking')}" target="_blank" rel="noopener">Officieel antwoordmodel ↗</a>${button('Dashboard','#tentamen')}</div></section><ol class="sra-exam-overview">${e.questions.map(q=>`<li><a href="${link(e,String(q.number))}"><strong>${q.originalNumber||q.number}</strong><span>${questionLabel(e,q)} · ${q.points} ${q.points===1?'punt':'punten'}</span><span>${a.answers[q.number]?.trim()?'Uitwerking bewaard':'Niet beantwoord'}</span></a></li>`).join('')}</ol></div>`;if(!review)$('#exam-finish').onclick=()=>{a.completed=new Date().toISOString();save();location.hash=link(e,'resultaat');};}
 function sourceOnly(e){$('#main').innerHTML=`${ctx.pageHead(e.title+' · Antwoordmodel')}<div class="study-dashboard">${crumb('Antwoordmodel')}<p>Alleen de officiële uitwerking is beschikbaar. Dit bestand telt mee in de analyse, maar is geen volledig oefententamen.</p><div class="sra-source-only">${viewer(e,'uitwerking',1)}</div><a href="${pdf(e,'uitwerking')}" target="_blank" rel="noopener">Open de originele PDF ↗</a></div>`;bindViewer(e,'uitwerking');}
 function analysis(id){
  const chronological=[...analysedExams].sort((a,b)=>a.id.localeCompare(b.id)),examCount=analysedExams.length,questionCounts=analysedExams.map(e=>e.questions.length),questionCount=questionCounts.reduce((sum,n)=>sum+n,0),pointCount=analysedExams.reduce((sum,e)=>sum+points(e),0),dateRange=examCount?monthYear(chronological[0])+' tot '+monthYear(chronological[examCount-1]):'Geen tentamens beschikbaar',predictionCount=D.frequencies['Voorspellingsinterval regressie']||0;
  const selected=D.exams.find(e=>e.id===id),topicRows=Object.entries(D.frequencies).map(([topic,count])=>`<tr><td>${esc(topic)}</td><td><strong>${count} / ${examCount}</strong></td><td><details><summary>Bekijk de vragen</summary>${analysedExams.filter(e=>e.evidence[topic]?.length).map(e=>`<p><a href="${link(e,e.onlyAnswers?'bron':String(e.evidence[topic][0]))}">${e.date}</a>: ${e.evidence[topic].map(n=>questionLabel(e,e.questions.find(q=>q.number===n)).toLowerCase()).join('; ')}</p>`).join('')}</details></td></tr>`).join('');
  $('#main').innerHTML=`${ctx.pageHead('Tentamenanalyse SRA')}<article class="sra-analysis">${crumb('Tentamenanalyse')}<header><p class="eyebrow">${examCount} inhoudelijk verschillende tentamens · ${dateRange}</p><h2>Wat wordt gevraagd, en hoe bereid je je voor?</h2><p class="lead">De vaste basis is <strong>35 punten steekproeven en 65 punten regressie</strong>. De ${questionCount} vragen combineren rekenen, kennis van begrippen en onderbouwde conclusies. Tabellen en grafieken kunnen lezen is een essentieel deel van de toets.</p></header><nav class="jump" aria-label="Onderdelen analyse"><a href="#analyse-structuur" data-analysis-scroll="analyse-structuur">Opbouw</a><a href="#analyse-typen" data-analysis-scroll="analyse-typen">Vraagtypen</a><a href="#analyse-onderwerpen" data-analysis-scroll="analyse-onderwerpen">Onderwerpen</a><a href="#analyse-per-tentamen" data-analysis-scroll="analyse-per-tentamen">Per tentamen</a><a href="#analyse-aanpak" data-analysis-scroll="analyse-aanpak">Leeradvies</a></nav>
  <section id="analyse-structuur"><h2>1. De structuur van het tentamen</h2><p>De vaste inhoudelijke verdeling is <strong>steekproeven en regressie</strong>. De nieuwere tentamens hebben twee hoofdopgaven. De tentamens van maart en juni 2020 hebben drie: steekproeven (35 punten), enkelvoudige regressie (40 punten) en meervoudige regressie (25 punten). De vraagnummering begint daar per opgave opnieuw. Een opgave is een groter blok met meerdere vragen; binnen een opgave kunnen verschillende bedrijven, datasets of modellen voorkomen.</p><div class="sra-weight-bar"><span>Steekproeven · 35 punten</span><span>Regressie · 65 punten</span></div><div class="sra-analysis-table"><table><thead><tr><th>Positie</th><th>Onderwerp en lesstof</th><th>Gebruikelijke uitwerking</th></tr></thead><tbody><tr><td><strong>Opgave 1</strong><br>35 / 100 punten</td><td>Sampling: steekproeven en schatters.<br>Hoofdstuk 8.</td><td>Eerst een populatietotaal schatten met MPU, verschil-, ratio- of regressieschatter. Daarnaast stratificatie: de populatie opdelen, de steekproef verdelen en een totaalinterval berekenen. Soms ook de benodigde steekproefomvang.</td></tr><tr><td><strong>Opgave 2</strong><br>In 2020: opgave 2 en 3 samen<br>65 / 100 punten</td><td>Regression: enkelvoudige en meervoudige regressie.<br>Hoofdstuk 9 en 10.</td><td>SPSS-uitvoer lezen, modelkwaliteit beoordelen, aannames onderzoeken, toetsen en modellen vergelijken. Afhankelijk van het tentamen ook een voorspelling, interval of transformatie berekenen.</td></tr></tbody></table></div><p><strong>De volgorde binnen regressie wisselt.</strong> Oktober 2022 begint met een meervoudig model (deel A, 45 punten) en gaat naar een enkelvoudig model (deel B, 20 punten). Oktober 2024 gaat juist van enkelvoudig (46 punten) naar meervoudig (19 punten). Leer daarom de samenhang; onthoud geen vaste vraagvolgorde.</p><p>Het aantal genummerde vragen varieert van <strong>${questionCounts.length?Math.min(...questionCounts):0} tot ${questionCounts.length?Math.max(...questionCounts):0}</strong>. Sommige vragen hebben deelvragen. Een tentamen met minder vraagnummers bevat dus niet automatisch minder werk.</p></section>
  <section id="analyse-typen"><h2>2. Welke typen vragen worden gesteld?</h2><p>De oorspronkelijke tentamens bestaan uit open vragen. Een vraag kan meerdere vaardigheden tegelijk toetsen. Hieronder staat wat de vraag van je vraagt, hoe je dit herkent en hoe je antwoord opbouwt. De voorbeelden verwijzen naar echte vraagnummers; het zijn geen letterlijke citaten.</p><div class="sra-analysis-table"><table><thead><tr><th>Vraagtype</th><th>Wat wordt verwacht?</th><th>Voorbeeld uit de reeks</th></tr></thead><tbody>
  <tr><td><strong>Theorie / begripskennis</strong></td><td>Een begrip, methode of voorwaarde uitleggen. Noem de kern én de betekenis in gewone woorden. Bij “leg uit” is alleen een formule meestal niet het volledige antwoord.</td><td><a href="#tentamen/20250317/1">Maart 2025, vraag 1</a>: wanneer heeft de verschilschatter de voorkeur?<br><a href="#tentamen/20240318/16">Maart 2024, vraag 16</a>: kleinste kwadraten (OLS) en wat wordt geminimaliseerd.</td></tr>
  <tr><td><strong>Rekenvraag</strong></td><td>Kies de methode, toon de gegevens en tussenstappen, bereken de uitkomst en rond volgens de opdracht af. Grote intervalvragen zijn berekeningen in meerdere stappen.</td><td><a href="#tentamen/20250317/3">Maart 2025, vraag 3</a>: interval met de verschilschatter.<br><a href="#tentamen/20240318/12">Maart 2024, vraag 12</a>: ontbrekende ANOVA-waarden berekenen.</td></tr>
  <tr><td><strong>Inzicht / methodekeuze</strong></td><td>Pas een regel toe op de concrete casus. Leg uit waarom een aanpak geschikt is, of waarom een model of voorspelling wel of niet verdedigbaar is.</td><td><a href="#tentamen/20250317/2">Maart 2025, vraag 2</a>: is de verschilschatter hier toegestaan?<br><a href="#tentamen/20231030/11">Oktober 2023, vraag 11</a>: voorspellen binnen of buiten het waargenomen bereik.</td></tr>
  <tr><td><strong>Interpretatie / diagnose</strong></td><td>Lees een tabel of grafiek, wijs het relevante getal of patroon aan en trek een conclusie. Noem bij een probleem de remedie als daarom wordt gevraagd. Een residu is het verschil tussen de werkelijke en voorspelde waarde.</td><td><a href="#tentamen/20250317/15">Maart 2025, vraag 15</a>: normaliteit beoordelen.<br><a href="#tentamen/20211101/13">November 2021, vraag 13</a>: uitschieters en invloedrijke punten analyseren.</td></tr>
  <tr><td><strong>Toetsen / onderbouwen</strong></td><td>Formuleer de nul- en alternatieve hypothese, kies een- of tweezijdig, bepaal de toetsingsgrootheid en beslis met de gevraagde grens of p-waarde. Sluit af met een conclusie over de casus.</td><td><a href="#tentamen/20250317/21">Maart 2025, vraag 21</a>: een regressieverband toetsen.<br><a href="#tentamen/20230315/15">Maart 2023, vraag 15</a>: toetsen op een stijgend verband met de kritieke grens.</td></tr>
  </tbody></table></div><p><strong>Het terugkerende patroon:</strong> lange rekenvragen bij schatten en intervallen, met kortere vragen over voorwaarden en interpretatie eromheen. Bij regressie wisselen tabellen, grafieken, berekeningen en verklaringen elkaar af. Deze typen overlappen; er is daarom geen kunstmatige procentverdeling over “theorie” en “rekenen” toegevoegd.</p></section>
  <section id="analyse-onderwerpen"><h2>3. Welke onderwerpen keren terug?</h2><p>De telling geeft aan in hoeveel van de ${examCount} tentamens expliciet een vraag of deelvraag over het onderwerp staat. Onderwerpen overlappen. Een frequentie is geen puntengewicht of garantie voor een volgend tentamen.</p><div class="sra-analysis-table"><table><thead><tr><th>Onderwerp</th><th>Tentamens</th><th>Controleerbare voorbeelden</th></tr></thead><tbody>${topicRows}</tbody></table></div></section>
  <section id="analyse-per-tentamen"><h2>4. Indeling per tentamen</h2><p>Zoals in BELRE3: kies een tentamen en vergelijk de opgave, punten, lesstof en onderwerpen. “Algemeen patroon” vat de vaste verdeling samen.</p><label class="sra-analysis-filter">Tentamen <select id="analysis-exam"><option value="">Algemeen patroon</option>${[...D.exams].reverse().map(e=>`<option value="${e.id}" ${selected===e?'selected':''}>${e.date}${e.duplicateOf?' · zelfde vragen als maart 2020':''}${e.onlyAnswers?' · alleen uitwerking':''}</option>`).join('')}</select></label><div id="analysis-exam-detail"></div></section>
  <section id="analyse-aanpak"><h2>5. Wat betekent dit voor je voorbereiding?</h2><ol class="sra-analysis-advice"><li><strong>Bouw de basis uit SET gericht op.</strong> Gemiddelde, variantie, standaardafwijking, standaardfout, betrouwbaarheid en hypothesen moeten eerst duidelijk zijn. Gebruik de basislessen alleen voor wat je in deze SRA-berekeningen nodig hebt.</li><li><strong>Train de volledige rekenketen.</strong> Van schatter en standaardfout naar interval en conclusie. Oefen alle vier schatters én stratificatie. Alleen een ingevulde formule herkennen is nog geen zelfstandige uitwerking.</li><li><strong>Geef regressie het grootste oefenblok.</strong> Het vertegenwoordigt steeds 65 punten. Verbind Model Summary (modelkwaliteit), ANOVA (variantieanalyse) en Coefficients (coëfficiënten) met de diagnosegrafieken.</li><li><strong>Beantwoord precies wat wordt gevraagd.</strong> Bij een diagnose: bronfiguur of tabel, signaal, conclusie en eventuele remedie. Bij een toets: hypothesen, berekening, beslissing en conclusie. Bij een theorieantwoord: begrip plus toepassing.</li><li><strong>Controleer met een volledig tentamen.</strong> Maak eerst een nulmeting, oefen daarna je zwakke onderdelen en maak een andere toets. Een voorspellingsinterval komt in ${predictionCount} van de ${examCount} tentamens voor. Ook onderwerpen die minder vaak voorkomen, blijven relevant.</li></ol></section>
  <section class="sra-analysis-sources"><h2>Bronnen en afbakening</h2><p>${D.exams.length} tentamendata uit jouw aangeleverde map zijn beschikbaar. De opgaven van 23 maart en 26 juni 2020 hebben dezelfde vraaginhoud en tellen daarom één keer mee in de analyse. Zo blijven ${examCount} inhoudelijk verschillende tentamens over, samen ${questionCount} vragen en ${pointCount} punten. Herstartende vraagnummers tellen per opgave; dubbele versies zijn niet extra geteld. Deze analyse beschrijft de onderzochte reeks; de precieze nieuwe toets kan afwijken.</p><ul>${D.exams.map(e=>`<li>${e.date}: <a href="${pdf(e,e.onlyAnswers?'uitwerking':'opgaven')}" target="_blank" rel="noopener">${esc(e.source)}</a>${!e.onlyAnswers?` · <a href="${pdf(e,'uitwerking')}" target="_blank" rel="noopener">${esc(e.answerSource)}</a>`:''}</li>`).join('')}</ul><p>Opbouw van de analyse: <a href="https://github.com/HMA9K/BELRE3/blob/27f3479fe53908a2486ad19e85351896add6e577/index.html" target="_blank" rel="noopener">BELRE3, Tentamenindeling per Opgave</a>. Vormgeving van het dashboard: <a href="https://github.com/HMA9K/CAFA2/blob/382add0fb67ed503438876e40dbba46497e02c02/js/exams.js" target="_blank" rel="noopener">CAFA2, Cirrus-indeling</a>.</p></section></article>`;
  const detail=()=>{const e=D.exams.find(e=>e.id===$('#analysis-exam').value),rows=e?sections(e):[{number:1,title:'Steekproeven',points:35,description:'Steekproefschatters, intervallen en stratificatie. Soms de benodigde steekproefomvang.'},{number:'2 (in 2020: 2 en 3)',title:'Regressie',points:65,description:'Regressie, modelkwaliteit, toetsen, diagnose en variabelenselectie. De volgorde binnen de opgave wisselt.'}];$('#analysis-exam-detail').innerHTML=`<div class="sra-analysis-table"><table><thead><tr><th>Opgave</th><th>Punten</th><th>Vragen / stof</th><th>Onderwerpen</th></tr></thead><tbody>${rows.map(s=>{const qs=e?sectionQuestions(e,s):[],range=qs.length?'Vraag '+(qs[0].originalNumber||qs[0].number)+' t/m '+(qs[qs.length-1].originalNumber||qs[qs.length-1].number)+' · ':'';return `<tr><td>${s.number}</td><td>${s.points}</td><td>${range}${esc(sectionTitle(s))}</td><td>${esc(s.description||'')}</td></tr>`;}).join('')}</tbody></table></div>${e?`${e.duplicateOf?'<p>Deze datum bevat dezelfde vragen als het tentamen van 23 maart 2020. Beide versies zijn beschikbaar; voor de onderwerpfrequenties is de inhoud eenmaal geteld.</p>':''}<div class="actions">${button(e.onlyAnswers?'Bekijk de uitwerking':'Open dit tentamen',link(e),true)}</div>`:`<p>De inhoudelijke verdeling 35 punten steekproeven en 65 punten regressie geldt voor alle ${examCount} onderzochte tentamens. In 2020 zijn de 65 regressiepunten verdeeld over twee opgaven.</p>`}`;};$('#analysis-exam').onchange=detail;detail();
  document.querySelectorAll('[data-analysis-scroll]').forEach(a=>a.onclick=event=>{event.preventDefault();document.getElementById(a.dataset.analysisScroll).scrollIntoView({behavior:'smooth',block:'start'});});
 }
 window.SRAExams={render(id,part,context,item){ctx=context;if(!id||id==='voltooid'){dashboard(id==='voltooid');return true;}if(id==='oud'){$('#main').innerHTML=ctx.pageHead('Eerder opgeslagen uitwerkingen')+'<div class="study-dashboard">'+ctx.breadcrumb('Eerdere uitwerkingen')+'<p>Hier staan je uitwerkingen uit de eerdere SRA-versie. Nieuwe pogingen maak je via het tentamendashboard.</p><div class="actions">'+button('Nieuw tentamendashboard','#tentamen',true)+'</div>'+D.exams.filter(e=>answered(e)).map(e=>'<section class="sra-exam-welcome"><h2>'+esc(e.title)+'</h2><p>'+answered(e)+' uitwerkingen bewaard</p>'+e.questions.filter(q=>attempt(e).answers[q.number]?.trim()).map(q=>button(questionLabel(e,q),'#tentamen/'+e.id+'/oud/'+q.number)).join(' ')+'</section>').join('')+'</div>';return true;}if(id==='analyse'){analysis(part);return true;}if(id==='mc'){window.SRAMC.render(part,item,ctx);return true;}const e=D.exams.find(e=>e.id===id);if(!e)return false;if(part==='welkom'||!part){location.hash=e.onlyAnswers?'tentamen/'+e.id+'/bron':'welkom/'+e.id;} else if(e.onlyAnswers)sourceOnly(e);else if(part==='afronden'||part==='resultaat')finish(e,part==='resultaat');else if(part==='oud')runner(e,Number(item)||1);else location.hash='welkom/'+e.id+'/'+(Number(part)||1);return true;}};
})();
