(function(){
 'use strict';
 const M=window.SRAMath;
 const fmt=(x,d=2)=>Number(x).toLocaleString('nl-NL',{maximumFractionDigits:d,minimumFractionDigits:0});
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const field=(id,label,value,extra='')=>`<label class="field">${label}<input id="lab-${id}" name="${id}" type="number" ${/step=/.test(extra)?'':'step="any"'} value="${value}" ${extra}></label>`;
 const slider=(id,label,value,min,max,step=1)=>`<div class="field lab-slider"><label for="lab-${id}">${label}</label><div class="lab-slider-pair"><input type="range" data-sync="${id}" aria-label="${esc(label)} schuifregelaar" min="${min}" max="${max}" step="${step}" value="${value}"><input type="number" id="lab-${id}" name="${id}" aria-label="${esc(label)} getal" step="any" value="${value}"></div><span class="lab-range-hint">Schuif ${fmt(min)} tot ${fmt(max)}, of typ een waarde.</span></div>`;
 const select=(id,label,options)=>`<label class="field">${label}<select id="lab-${id}" name="${id}" aria-label="${esc(label)}">${options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label>`;
 const metric=(v,l)=>`<div class="metric"><b>${v}</b><span>${l}</span></div>`;
 const results=(rows)=>`<div class="results">${rows.map(r=>metric(...r)).join('')}</div>`;
 const line=(text)=>`<p class="lab-equation">${text}</p>`;
 const fixed=(x,d=2)=>Number(x).toLocaleString('nl-NL',{minimumFractionDigits:d,maximumFractionDigits:d});
 function dataTable(title,headers,rows,footer,extra=''){
  const cells=r=>`<tr><th scope="row">${esc(r[0])}</th>${r.slice(1).map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`;
  return `<div class="table-scroll" tabindex="0" role="region" aria-label="${esc(title)}"><table class="numeric ${extra} ${headers.length<=2?'compact':''}"><caption>${esc(title)}</caption><thead><tr>${headers.map(h=>`<th scope="col">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(cells).join('')}</tbody>${footer?`<tfoot>${cells(footer)}</tfoot>`:''}</table></div><p class="table-hint">Alle cijfers blijven leesbaar: schuif de tabel op een smal scherm naar links of rechts. Tussenstappen worden intern niet afgerond.</p>`;
 }
 const details=(title,body)=>`<details class="table-detail"><summary>${title}</summary>${body}</details>`;
 const chart=(title,svg,legend,note)=>`<figure class="chart-figure"><figcaption>${title}</figcaption><div class="chart-scroll" tabindex="0" role="region" aria-label="${esc(title)}">${svg}</div>${legend?`<div class="chart-legend">${legend}</div>`:''}<p class="chart-note">${note}</p></figure>`;
 const colors=['#008859','#444159','#c85209','#176fad'];
 const choice=(el,name)=>el.querySelector(`[name="${name}"]`).value;
 const seq=(a,b,n=40)=>Array.from({length:n+1},(_,i)=>a+(b-a)*i/n);
 const curve=(fn,a,b,n=40)=>seq(a,b,n).map(x=>[x,fn(x)]);
 const explain=(text)=>`<div class="lab-interpretation"><strong>Wat zie je?</strong><p>${text}</p></div>`;
 const tryThis=text=>`<p class="lab-try"><strong>Probeer dit:</strong> ${text}</p>`;
 function requireInteger(v,min,label){if(!Number.isInteger(v)||v<min)throw Error(`${label} moet een geheel getal van minstens ${min} zijn.`);}
 function requirePositive(v,label,zero=false){if(!Number.isFinite(v)||(zero?v<0:v<=0))throw Error(`${label} moet ${zero?'nul of positief':'positief'} zijn.`);}
 function graph(title,series,options={}){
  const points=series.flatMap(s=>s.points).filter(p=>p.every(Number.isFinite));if(!points.length)throw Error('Geen geldige grafiekwaarden.');
  if(series.some(s=>s.points.some(p=>!p.every(Number.isFinite))))throw Error('De grafiekwaarden zijn te groot. Kies kleinere invoer.');
  let xmin=options.xmin??Math.min(...points.map(p=>p[0])),xmax=options.xmax??Math.max(...points.map(p=>p[0])),ymin=options.ymin??Math.min(...points.map(p=>p[1])),ymax=options.ymax??Math.max(...points.map(p=>p[1]));
  if(xmax===xmin){xmin-=1;xmax+=1;}if(ymax===ymin){const d=Math.max(1,Math.abs(ymin)*.1);ymin-=d;ymax+=d;}
  if(options.ymin===undefined){const d=(ymax-ymin)*.1;ymin-=d;ymax+=d;}
  const W=640,H=345,L=80,R=620,T=40,B=280,X=x=>L+(x-xmin)/(xmax-xmin)*(R-L),Y=y=>B-(y-ymin)/(ymax-ymin)*(B-T);
  let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(title+'. '+(options.xlabel||'x')+' op de horizontale as; '+(options.ylabel||'y')+' op de verticale as.')}" xmlns="http://www.w3.org/2000/svg">`;
  for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;svg+=`<path d="M${L} ${Y(y)}H${R}" stroke="#e2e7eb"/><text x="${L-9}" y="${Y(y)+5}" text-anchor="end">${esc(fmt(y,2))}</text><text x="${X(x)}" y="${B+23}" text-anchor="middle">${esc(fmt(x,2))}</text>`;}
  if(options.band){const top=options.band.high.map(([x,y])=>`${X(x)},${Y(y)}`),bottom=options.band.low.slice().reverse().map(([x,y])=>`${X(x)},${Y(y)}`);svg+=`<polygon points="${top.concat(bottom).join(' ')}" fill="#00885918"/>`;}
  for(const y of options.horiz||[])if(y>=ymin&&y<=ymax)svg+=`<path d="M${L} ${Y(y)}H${R}" stroke="#b55617" stroke-dasharray="6 4"/>`;
  for(const x of options.vertical||[])if(x>=xmin&&x<=xmax)svg+=`<path d="M${X(x)} ${T}V${B}" stroke="#6a6576" stroke-dasharray="4 4"/>`;
  series.forEach((s,i)=>{const color=s.color||colors[i%colors.length];if(s.line!==false)svg+=`<polyline points="${s.points.map(([x,y])=>`${X(x)},${Y(y)}`).join(' ')}" fill="none" stroke="${color}" stroke-width="${s.width||2.7}" ${s.dash?'stroke-dasharray="6 4"':''}/>`;if(s.dots||s.line===false)s.points.forEach(([x,y])=>{svg+=`<circle cx="${X(x)}" cy="${Y(y)}" r="${s.radius||4.5}" fill="${color}"><title>${esc((s.name||'Waarde')+': '+fmt(x,4)+'; '+fmt(y,4))}</title></circle>`;});});
  svg+=`<path d="M${L} ${T}V${B}H${R}" fill="none" stroke="#87909a"/><text x="${(L+R)/2}" y="334" text-anchor="middle">${esc(options.xlabel||'x')}</text><text x="${L}" y="22">${esc(options.ylabel||'y')}</text></svg>`;
  return chart(title,svg,series.filter(s=>s.name).map((s,i)=>`<span><i class="key" style="border-color:${s.color||colors[i%colors.length]}"></i>${esc(s.name)}</span>`).join(''),options.note||'Eigen didactisch voorbeeld. Assen passen zich aan de gekozen waarden aan; exacte waarden staan bij de grafiek.');
 }
 function bars(title,labels,values,note=''){
  const low=Math.min(0,...values),high=Math.max(0,...values),span=high-low||1,X=v=>145+(v-low)/span*440;
  let svg=`<svg viewBox="0 0 640 ${labels.length*58+68}" role="img" aria-label="${esc(title)}">`;
  labels.forEach((l,i)=>{const y=26+i*58;svg+=`<text x="132" y="${y+17}" text-anchor="end">${esc(l)}</text><rect x="${Math.min(X(0),X(values[i]))}" y="${y}" width="${Math.max(.6,Math.abs(X(values[i])-X(0)))}" height="25" fill="${colors[i%4]}"/><text x="${X(values[i])}" y="${y+43}" text-anchor="${values[i]===high?'end':'start'}">${esc(fmt(values[i],3))}</text>`;});
  svg+=`<path d="M${X(0)} 12V${labels.length*58+10}" stroke="#818b96"/><text x="145" y="${labels.length*58+50}">${esc('Waarde: '+fmt(low)+' tot '+fmt(high))}</text></svg>`;
  return chart(title,svg,'',note||'De lengte geeft de waarde weer. De getallen geven dezelfde informatie als de balken.');
 }
 function histogram(edges,counts){
  const L=55,R=620,T=30,B=260,maximum=Math.max(1,...counts),w=(R-L)/counts.length,Y=n=>B-n/maximum*(B-T);
  let svg='<svg viewBox="0 0 640 330" role="img" aria-label="Histogram van demo-residuen met gelijke klassebreedte 1">';
  for(let n=0;n<=maximum;n++){svg+=`<path d="M${L} ${Y(n)}H${R}" stroke="#e4e9ed"/><text x="${L-9}" y="${Y(n)+4}" text-anchor="end">${n}</text>`;}
  counts.forEach((n,i)=>svg+=`<rect x="${L+i*w}" y="${Y(n)}" width="${w}" height="${B-Y(n)}" fill="#69b59b" stroke="white"/><text x="${L+i*w+w/2}" y="${Y(n)-7}" text-anchor="middle">${n||''}</text>`);
  edges.forEach((edge,i)=>svg+=`<text x="${L+i*w}" y="284" text-anchor="middle">${edge}</text>`);
  svg+=`<path d="M${L} ${T}V${B}H${R}" fill="none" stroke="#818a96"/><text x="${L}" y="19">Aantal residuen</text><text x="335" y="316" text-anchor="middle">Residu: klassen met breedte 1</text></svg>`;
  return chart('Histogram van dezelfde 12 demo-residuen',svg,'','De aaneengesloten balken hebben gelijke klassebreedte. Hoogte en oppervlakte geven daarom beide de frequentie weer. De linkergrens telt mee; de rechtergrens hoort bij het volgende interval.')+details('Bekijk de frequenties',dataTable('Frequentietabel',['Residu-interval','Aantal'],counts.map((n,i)=>[`${edges[i]} tot ${edges[i+1]}`,n])));
 }
 function marginGraph(v){const start=2,end=v.N,ns=[...new Set(seq(start,end,50).map(Math.round).concat(v.n))].sort((a,b)=>a-b);return graph('Meer controles en de onzekerheidsmarge',[{name:'Marge E bij vaste t',points:ns.map(n=>[n,M.estimate({...v,n}).margin])},{name:'Jouw n',points:[[v.n,M.estimate(v).margin]],line:false,color:colors[2],radius:6}],{xlabel:'Aantal controles n',ylabel:'Marge E (€)',ymin:0,note:'Hier blijven N, gemiddelde, spreiding en t gelijk. Bij n = N is er geen steekproefonzekerheid meer. Voor een echte nieuwe n moet je t opnieuw opzoeken.'});}
 function intervalSvg(point,margin,width){
  const low=point-margin,high=point+margin,mid=width/2,left=45,right=width-45;
  let svg=`<svg class="chart-responsive" viewBox="0 0 ${width} 155" role="img" aria-label="Ondergrens ${fmt(low)}, puntschatting ${fmt(point)}, bovengrens ${fmt(high)}"><line x1="20" y1="62" x2="${width-20}" y2="62" stroke="#c2c9cd" stroke-width="2"/>`;
  if(margin===0){svg+=`<circle cx="${mid}" cy="62" r="7" fill="#444159"/><text x="${mid}" y="101" text-anchor="middle">${fmt(point)}</text><text x="${mid}" y="132" text-anchor="middle">Marge = 0</text>`;}
  else{svg+=`<line x1="${left}" y1="62" x2="${right}" y2="62" stroke="#008859" stroke-width="6"/><path d="M${left} 49V75M${right} 49V75" stroke="#008859" stroke-width="3"/><circle cx="${mid}" cy="62" r="7" fill="#444159"/>`;
   [[left,low,'Onder'],[mid,point,'Schatter'],[right,high,'Boven']].forEach(([x,v,l])=>svg+=`<text x="${x}" y="101" text-anchor="middle">${fmt(v)}</text><text x="${x}" y="128" text-anchor="middle">${l}</text>`);
   svg+=`<text x="${(left+mid)/2}" y="30" text-anchor="middle">− marge E</text><text x="${(right+mid)/2}" y="30" text-anchor="middle">+ marge E</text>`;
  }
  return chart('Van puntschatting naar interval',svg+'</svg>','',`De grenzen zijn de puntschatting ± ${fmt(margin)}. De schaal past zich aan de invoer aan; vergelijk de getallen om veranderingen in breedte te beoordelen.`)+dataTable('Interval in getallen',['Onderdeel','Waarde'],[['Ondergrens',fixed(low)],['Puntschatting',fixed(point)],['Bovengrens',fixed(high)]]);
 }
 function plot(xs,ys,b0,b1,width){
  const maxX=Math.max(...xs)+1,minY=Math.min(0,...ys,b0,b0+b1*maxX)-4,maxY=Math.max(...ys,b0,b0+b1*maxX)+4,X=x=>55+x/maxX*(width-75),Y=y=>230-(y-minY)/(maxY-minY)*190;
  let svg=`<svg class="chart-responsive" viewBox="0 0 ${width} 295" role="img" aria-label="Waarnemingen als paarse punten, geschatte lijn in groen en residuen als oranje stippellijnen. Exacte waarden staan in de uitklapbare rekentabel.">`;
  for(let j=0;j<=4;j++){const y=minY+(maxY-minY)*j/4;svg+=`<line x1="55" y1="${Y(y)}" x2="${width-20}" y2="${Y(y)}" stroke="#e7eaf0"/><text x="47" y="${Y(y)+5}" text-anchor="end">${fmt(y,1)}</text>`;}
  svg+=`<path d="M55 35V230H${width-10}" fill="none" stroke="#868e9a"/><line x1="${X(0)}" y1="${Y(b0)}" x2="${X(maxX)}" y2="${Y(b0+b1*maxX)}" stroke="#008859" stroke-width="3"/>`;
  xs.forEach((x,i)=>{svg+=`<line x1="${X(x)}" x2="${X(x)}" y1="${Y(ys[i])}" y2="${Y(b0+b1*x)}" stroke="#c85209" stroke-width="2" stroke-dasharray="4 3"/><circle cx="${X(x)}" cy="${Y(ys[i])}" r="5" fill="#444159"/>${width>=420||x%2===0?`<text x="${X(x)}" y="252" text-anchor="middle">${x}</text>`:``}`;});
  svg+=`<text x="${width/2}" y="281" text-anchor="middle">Verklarende variabele x</text><text x="55" y="20">Uitkomst y</text></svg>`;
  const legend='<span><i class="key dot"></i>Waargenomen y</span><span><i class="key"></i>Voorspelde ŷ</span><span><i class="key residual"></i>Residu y − ŷ</span>';
  const rows=xs.map((x,i)=>{const yh=b0+b1*x,e=ys[i]-yh;return [x,fixed(ys[i]),fixed(yh),fixed(e),fixed(e*e)];});
  const sse=ys.reduce((s,y,i)=>s+(y-b0-b1*xs[i])**2,0);
  return chart('Regressielijn en de afstand tot ieder punt',svg,legend,'Dit zijn demonstratiewaarden zonder fysieke eenheid. De y-schaal past zich aan zodat de volledige lijn zichtbaar blijft.')+details('Bekijk de residuen en hun kwadraten',dataTable('Van waarnemingen naar SSE',['x','Waargenomen y','Voorspelde ŷ','Residu e','Kwadratisch e²'],rows,['Som','', '', '',fixed(sse)]));
 }
 function spreadTable(values,r){
  const rows=values.map((v,i)=>[i+1,fixed(v),fixed(v-r.mean),fixed((v-r.mean)**2)]);
  return dataTable('Van losse waarden naar spreiding',['Waarneming','Waarde wᵢ','Afwijking wᵢ − w̄','Kwadratisch'],rows,['Som',fixed(r.sum),fixed(0),fixed(r.ss)])+line(`Variantie s² = ${fmt(r.ss)} / ${r.n-1} = ${fmt(r.variance)}. Standaardafwijking s = √${fmt(r.variance)} = ${fmt(r.sd)}.`);
 }
 function estimateSteps(v,r){
  return dataTable('Rekenroute met jouw invoer',['Stap','Invullen','Uitkomst'],[
   ['1 · Puntschatting',`${fmt(v.N)} × ${fmt(v.mean)}`,`€ ${fixed(r.point)}`],
   ['2 · Eindigheidscorrectie',`√((${fmt(v.N)} − ${fmt(v.n)}) / (${fmt(v.N)} − 1))`,fixed(r.correction,5)],
   ['3 · Standaardfout',`${fmt(v.N)} × (${fmt(v.sd)} / √${fmt(v.n)}) × ${fmt(r.correction,5)}`,`€ ${fixed(r.se)}`],
   ['4 · Marge',`${fmt(v.t,4)} × ${fmt(r.se,5)}`,`€ ${fixed(r.margin)}`],
   ['5 · Ondergrens',`${fmt(r.point)} − ${fmt(r.margin,5)}`,`€ ${fixed(r.low)}`],
   ['6 · Bovengrens',`${fmt(r.point)} + ${fmt(r.margin,5)}`,`€ ${fixed(r.high)}`]
  ],null,'calculation-table')+line(`Je schat het populatietotaal op € ${fixed(r.point)}. Met de gekozen kritieke t loopt het interval van € ${fixed(r.low)} tot € ${fixed(r.high)}.`);
 }
 function anovaTable(v,r){
  return dataTable('ANOVA · opsplitsing van de totale variatie',['Bron','SS','df','MS','F'],[
   ['Regression',fixed(v.SSR,3),v.k,fixed(r.MSR,4),fixed(r.F,2)],
   ['Residual',fixed(v.SSE,3),r.df,fixed(r.MSE,4),'n.v.t.']
  ],['Total',fixed(r.total,3),v.n-1,'n.v.t.','n.v.t.'])+
  `<figure class="chart-figure"><figcaption>Welk deel van de variatie verklaart het model?</figcaption><div class="variance-bar" role="img" aria-label="${fmt(r.R2*100)} procent verklaarde variatie en ${fmt((1-r.R2)*100)} procent resterende variatie"><span style="width:${r.R2*100}%"></span></div><div class="chart-legend"><span>Groen: verklaard ${fixed(r.R2*100)}%</span><span>Licht: resterend ${fixed((1-r.R2)*100)}%</span></div><p class="chart-note">De volledige balk is 100% van TotalSS. SS = kwadratensom; df = vrijheidsgraden; MS = SS / df. SPSS laat MS en F op de Total-rij leeg.</p></figure>`;
 }
 const configs={
  spreiding:{title:'Maak spreiding zichtbaar',hint:'Verander een waarde. Bekijk wat er met het gemiddelde en de standaardafwijking gebeurt. Scheid waarden met puntkomma’s; gebruik een komma of punt voor decimalen.',fields:`<label class="field">Waarden<input id="lab-values" name="values" class="number-list" type="text" value="80; 90; 110; 120"></label>`,run:el=>{const raw=el.querySelector('[name=values]').value.split(';').map(s=>s.trim());if(raw.some(s=>!s))throw Error('Vul na elke puntkomma een waarde in.');const values=raw.map(s=>Number(s.replace(',','.'))),r=M.stats(values);return results([[fmt(r.mean),'Gemiddelde'],[fmt(r.variance),'Steekproefvariantie s²'],[fmt(r.sd),'Standaardafwijking s']])+spreadTable(values,r);}},
  interval:{title:'Wat verandert de onzekerheidsmarge?',hint:'Onderzoek een MPU-interval. Houd de gemiddelde waarde gelijk en verander n of s. t is een apart invoerveld: zoek die opnieuw op als je n of de betrouwbaarheid verandert.',fields:field('N','Populatieomvang N',1000,'min="2" step="1"')+field('n','Steekproefomvang n',100,'min="2" step="1"')+field('mean','Gemiddelde w̄ (€)',80)+field('sd','Standaardafwijking s (€)',20,'min="0"')+field('t','Kritieke t (hier gegeven)',1.987,'min="0.001"'),run:(el,v)=>{const r=M.estimate(v);return results([[fmt(r.point),'Geschat totaal (€)'],[fmt(r.margin),'Marge E (€)'],[fmt(2*r.margin),'Totale breedte (€)']])+intervalSvg(r.point,r.margin,Math.max(240,Math.min(600,el.querySelector('.lab-result').clientWidth-34)))+line(`s_totaal = ${fmt(r.se)}; eindigheidscorrectie = ${fmt(r.correction,4)}. De grafiek toont de grenzen; de horizontale schaal past zich aan.`);}},
  schatter:{title:'Reken de directe schatter stap voor stap na',hint:'Dit werkblad gebruikt het gemiddelde en de standaardafwijking als invoer. Zoek de kritieke t bij de betrouwbaarheid en df = n − 1 op in je tabellenbundel.',fields:field('N','N · aantal posten populatie',1000,'min="2" step="1"')+field('n','n · gecontroleerde posten',100,'min="2" step="1"')+field('mean','w̄ · gemiddelde werkelijke waarde',80)+field('sd','s_w · spreiding werkelijke waarden',20,'min="0"')+field('t','t · tabelwaarde',1.987,'min="0.001"'),run:(el,v)=>{const r=M.estimate(v);return results([[fmt(r.point),'Puntschatting (€)'],[fmt(r.se),'Standaardfout (€)'],[fmt(r.margin),'Marge (€)']])+estimateSteps(v,r);}},
  strata:{title:'Verdeel 100 controles over twee strata',hint:'Vergelijk evenredige allocatie met Neyman. Verhoog de spreiding in één groep. De gehele verdeling gebruikt de grootste resterende fracties en blijft optellen tot n.',fields:select('method','Allocatiemethode',[['evenredig','Evenredig'],['neyman','Neyman']])+field('n','Totaal aantal controles n',100,'min="1" step="1"')+field('N1','Aantal posten stratum 1',600,'min="1" step="1"')+field('s1','Spreiding stratum 1',10,'min="0"')+field('N2','Aantal posten stratum 2',400,'min="1" step="1"')+field('s2','Spreiding stratum 2',30,'min="0"'),run:(el,v)=>{const method=el.querySelector('[name=method]').value,r=M.allocate([v.N1,v.N2],[v.s1,v.s2],v.n,method);return results([[r.rounded[0],'Controles stratum 1'],[r.rounded[1],'Controles stratum 2'],[r.rounded.reduce((a,b)=>a+b,0),'Samen']])+line(`Vóór afronding: ${fmt(r.raw[0],3)} en ${fmt(r.raw[1],3)}. ${method==='neyman'?'Neyman weegt met Nᵢ × sᵢ.':'Evenredige allocatie gebruikt alleen Nᵢ.'}`);}},
  regressie:{title:'Vind de lijn met de kleinste kwadratensom',hint:'De paarse punten blijven staan. Verander de groene lijn. De oranje lijntjes zijn de residuen. Probeer SSE kleiner te maken en vergelijk met de OLS-oplossing.',fields:`<label class="field">Constante b₀<input name="b0" type="range" min="-5" max="20" step="0.1" value="8"></label><label class="field">Helling b₁<input name="b1" type="range" min="-2" max="8" step="0.1" value="1"></label><button type="button" class="btn small" id="lab-fit">Zet op de OLS-oplossing</button>`,run:(el,v)=>{const xs=[1,2,3,4,5,6,7,8],ys=[9,10,15,15,21,21,26,27],fit=M.ols(xs,ys),sse=ys.reduce((s,y,i)=>s+(y-(v.b0+v.b1*xs[i]))**2,0);return plot(xs,ys,v.b0,v.b1,Math.max(240,Math.min(600,el.querySelector('.lab-result').clientWidth-34)))+results([[`${fmt(v.b0)} + ${fmt(v.b1)}x`,'Jouw lijn ŷ'],[fmt(sse),'Jouw SSE'],[fmt(fit.sse),'Kleinst mogelijke SSE']])+line(`OLS: ŷ = ${fmt(fit.b0,4)} + ${fmt(fit.b1,4)}x. Correlatie r = ${fmt(fit.r,3)}. De OLS-knop vult de berekende coëfficiënten zonder tussentijdse afronding in.`);}},
  anova:{title:'Vul een ANOVA-tabel vanuit de bouwstenen',hint:'Verander de kwadratensommen of het aantal verklarende variabelen. k telt de constante niet mee. De uitkomst is een rekenvoorbeeld; de invoer is geen nieuwe dataset.',fields:field('n','Aantal waarnemingen n',30,'min="3" step="1"')+field('k','Aantal verklarende variabelen k',1,'min="1" step="1"')+field('SSR','Verklaarde kwadratensom SSR',1351.262,'min="0"')+field('SSE','Residuele kwadratensom SSE',44.105,'min="0.001"'),run:(el,v)=>{const r=M.anova(v.n,v.k,v.SSR,v.SSE);return anovaTable(v,r)+results([[fmt(r.R2*100)+'%','Verklaarde variatie'],[fmt(r.F),'F = MSR/MSE'],[fmt(r.se,4),'s_e = √MSE']])+line(`Adjusted R² = ${fmt(r.adjusted,4)}. Significant? Vergelijk F met de grens voor (${v.k}, ${r.df}) vrijheidsgraden en de gekozen α.`);}},
  toets:{title:'Van SPSS Sig. naar een beslissing',hint:'Gebruik een tweezijdige Sig.-waarde uit Coefficients. Kies de vooraf bedoelde toetsrichting en het teken van de gevonden coëfficiënt.',fields:field('p','Tweezijdige p-waarde',0.03,'min="0" max="1"')+field('alpha','Significantieniveau α',0.05,'min="0.0001" max="0.9999"')+select('direction','Alternatieve hypothese',[['two','β₁ ≠ 0'],['positive','β₁ > 0'],['negative','β₁ < 0']])+select('sign','Teken van de gevonden B',[['positive','Positief'],['negative','Negatief']]),run:(el,v)=>{if(v.p<0||v.p>1||v.alpha<=0||v.alpha>=1)throw Error('Gebruik 0 ≤ p ≤ 1 en 0 < α < 1.');const direction=el.querySelector('[name=direction]').value,sign=el.querySelector('[name=sign]').value,p=direction==='two'?v.p:direction===sign?v.p/2:1-v.p/2,reject=p<v.alpha;return results([[fmt(p,5),'p voor jouw hypothese'],[reject?'Verwerpen':'Niet verwerpen','Beslissing over H₀'],[reject?'α-risico':'β-risico','Relevant risico']])+line(`${fmt(p,5)} ${reject?'&lt;':'≥'} ${fmt(v.alpha)}. ${reject?'Voldoende bewijs voor H₁ op dit niveau.':'Onvoldoende bewijs voor H₁ op dit niveau.'} ${direction!=='two'&&direction!==sign?'Het waargenomen teken is tegengesteld aan de gekozen richting; daarom gebruik je 1 − p/2.':''}`);}},
  diagnose:{title:'Oefen de grens voor een uitbijter in y',hint:'Pas n en het gestandaardiseerde residu aan. Een grensoverschrijding is een onderzoekssignaal, geen automatische verwijderopdracht.',fields:field('n','Aantal waarnemingen n',100,'min="3" step="1"')+field('z','Gestandaardiseerd residu z',2.5),run:(el,v)=>{if(!Number.isInteger(v.n)||v.n<3)throw Error('Gebruik een geheel aantal waarnemingen van minstens 3.');const boundary=v.n<=100?2:3,flag=Math.abs(v.z)>boundary;return results([[`±${boundary}`,'Cursusgrenzen'],[fmt(v.z),'Gestandaardiseerd residu'],[flag?'Onderzoeken':'Binnen grenzen','Beoordeling']])+line(flag?'Onderzoek de betreffende waarneming en haar oorzaak. Corrigeer een aantoonbare invoerfout; behoud valide waarnemingen zonder bijzondere oorzaak.':'Op basis van dit residu is er geen signaal van een y-uitbijter volgens de cursusgrens. Andere modelproblemen zijn daarmee niet uitgesloten.');}},
  voorspelling:{title:'Zie hoe de afstand tot x̄ de marge vergroot',hint:'Werkblad voor een individuele voorspelling bij enkelvoudige regressie. De t-waarde is invoer; controleer die bij df = n − 2.',fields:field('b0','Constante b₀',7.159)+field('b1','Helling b₁',0.099)+field('x0','Nieuwe waarde x₀',228.1)+field('xbar','Gemiddelde x̄',228.1)+field('n','Aantal waarnemingen n',30,'min="3" step="1"')+field('sx','Standaardafwijking x (demo)',30,'min="0.001"')+field('se','Std. Error of the Estimate',1.25506,'min="0"')+field('t','Kritieke t',2.048,'min="0.001"'),run:(el,v)=>{const r=M.predict(v);return results([[fmt(r.point,4),'Puntvoorspelling'],[fmt(r.margin,4),'Marge'],[fmt(r.extra,5),'Afstandsterm']])+intervalSvg(r.point,r.margin,Math.max(240,Math.min(600,el.querySelector('.lab-result').clientWidth-34)))+line(`Wortelfactor = √(1 + 1/${v.n} + ${fmt(r.extra,5)}) = ${fmt(r.factor,5)}. s_x = 30 is hier een gekozen demonstratiewaarde; bij x₀ = x̄ beïnvloedt s_x het antwoord niet.`);}},
  transformatie:{title:'Van modelvorm naar voorspelling',hint:'Kies een model en vul x in. Bij een logaritmisch of machtsmodel moet x positief zijn.',fields:select('model','Model',[['power','Machtsfunctie (Power)'],['exponential','Exponentieel'],['log','Logaritmisch']])+field('b0','Constante b₀',1)+field('b1','Coëfficiënt b₁',0.5)+field('x','Waarde van x',16,'min="0.001"'),run:(el,v)=>{const model=el.querySelector('[name=model]').value;if(model!=='exponential'&&v.x<=0)throw Error('ln(x) vereist x > 0.');const lin=v.b0+v.b1*(model==='exponential'?v.x:Math.log(v.x)),y=model==='log'?lin:Math.exp(lin);if(!Number.isFinite(y))throw Error('De voorspelling is te groot; kies kleinere invoer.');return results([[fmt(lin,5),model==='log'?'Voorspelde y':'Voorspelde ln(y)'],[fmt(y,5),'Uitkomst op oorspronkelijke schaal']])+line(model==='log'?`ŷ = ${v.b0} + ${v.b1} × ln(${v.x}) = ${fmt(y,5)}.`:`ŷ = exp(${fmt(lin,5)}) = ${fmt(y,5)}. ${model==='power'?`Dit is ook exp(${v.b0}) × ${v.x}^${v.b1}.`:''}`);}}
 };
 // Each experiment below changes a visible statistical object, not only a number.
 const original={...configs};
 configs.spreiding={...original.spreiding,run:(el,v)=>{
  const raw=choice(el,'values').split(';').map(s=>s.trim());if(raw.some(s=>!s)||raw.length>80)throw Error('Gebruik 2 tot 80 waarden, gescheiden door puntkomma’s.');const values=raw.map(s=>Number(s.replace(',','.'))),r=M.stats(values);
  return results([[fmt(r.mean),'Gemiddelde'],[fmt(r.sd),'Standaardafwijking'],[r.n,'Waarnemingen']])+graph('Waarden en hun gemiddelde',[{name:'Waarneming',points:values.map((y,i)=>[i+1,y]),line:false},{name:'Gemiddelde',points:[[1,r.mean],[values.length,r.mean]],color:colors[1]}],{xlabel:'Nummer van de waarneming',ylabel:'Waarde w',note:'De horizontale lijn is het gemiddelde. De afstand van een punt tot die lijn is zijn afwijking; kwadrateren voorkomt dat plus en min elkaar opheffen.'})+tryThis('Verander 120 in 200. Bekijk welke punten verder van het gemiddelde komen te liggen.')+explain(`De waarden liggen gemiddeld niet exact ${fmt(r.sd)} van het gemiddelde: s is de wortel uit de steekproefvariantie. Alle afwijkingen tellen samen op tot nul; hun kwadraten tellen op tot ${fmt(r.ss)}.`)+spreadTable(values,r);
 }};
 for(const id of ['interval','schatter'])configs[id]={...original[id],fields:field('N','Populatieomvang N',1000,'min="2" step="1"')+slider('n','Steekproefomvang n',100,2,1000,1)+slider('mean','Gemiddelde werkelijke waarde (€)',80,0,200,1)+slider('sd','Standaardafwijking s (€)',20,0,100,1)+field('t','Kritieke t uit tabellenbundel',1.987,'min="0.0001"'),run:(el,v)=>{const r=M.estimate(v);return results([[fmt(r.point),'Geschat totaal (€)'],[fmt(r.se),'Standaardfout (€)'],[fmt(r.margin),'Marge E (€)']])+marginGraph(v)+explain(`Bij n = ${v.n} schat je het totaal op € ${fixed(r.point)}. Het interval loopt van € ${fixed(r.low)} tot € ${fixed(r.high)}. ${v.n===v.N?'Je controleert de volledige populatie.':'Meer controles verkleinen hier de marge, terwijl het ingevoerde gemiddelde gelijk blijft.'}`)+tryThis('Verdubbel n zonder andere velden te veranderen. Zet daarna n gelijk aan N.')+details('Bekijk alle rekenstappen',estimateSteps(v,r));}};
 configs.regressie={...original.regressie,fields:slider('b0','Constante b₀',8,-5,20,.1)+slider('b1','Helling b₁',1,-2,8,.1)+'<button type="button" class="btn small" id="lab-fit">Zet op de OLS-oplossing</button>',run:(el,v)=>original.regressie.run(el,v)+explain('De constante verschuift de lijn omhoog of omlaag. De helling bepaalt hoeveel ŷ verandert bij één extra x. OLS kiest de coëfficiënten die de som van alle gekwadrateerde residuen zo klein mogelijk maken.')};
 configs.strata={...original.strata,title:'Hoe verdeel je controles over groepen?',fields:select('method','Allocatiemethode',[['evenredig','Evenredig'],['neyman','Neyman']])+slider('n','Totaal aantal controles n',100,4,400,1)+field('N1','Aantal posten stratum 1',600,'min="1" step="1"')+slider('s1','Spreiding stratum 1',10,0,60,1)+field('N2','Aantal posten stratum 2',400,'min="1" step="1"')+slider('s2','Spreiding stratum 2',30,0,60,1),run:(el,v)=>{const method=choice(el,'method'),r=M.allocate([v.N1,v.N2],[v.s1,v.s2],v.n,method),even=M.allocate([v.N1,v.N2],[v.s1,v.s2],v.n,'evenredig');return results([[r.rounded[0],'Controles stratum 1'],[r.rounded[1],'Controles stratum 2'],[r.rounded.reduce((a,b)=>a+b,0),'Samen']])+bars('Verdeling van de controles',['Stratum 1','Stratum 2'],r.rounded,`Gekozen methode: ${method==='neyman'?'Neyman':'evenredig'}. n₁ + n₂ blijft gelijk aan n.`)+dataTable('Vergelijk de verdeling',['Groep','Nᵢ','Spreiding sᵢ','Evenredig nᵢ','Gekozen nᵢ'],[['Stratum 1',v.N1,v.s1,even.rounded[0],r.rounded[0]],['Stratum 2',v.N2,v.s2,even.rounded[1],r.rounded[1]]])+explain(method==='neyman'?'Neyman gebruikt Nᵢ × sᵢ. Bij gelijke omvang krijgt een groep met meer spreiding meer controles. De restfracties bepalen de afronding naar gehele aantallen.':'Evenredig gebruikt alleen de groepsomvang. Verandering van s₁ of s₂ heeft hier daarom geen effect; schakel naar Neyman om die invloed te zien.')+tryThis('Kies Neyman en verhoog s₂. Bekijk waarom stratum 2 meer controles krijgt.');}};
 configs.anova={...original.anova,fields:field('n','Aantal waarnemingen n',30,'min="3" step="1"')+slider('k','Aantal verklarende variabelen k',1,1,8,1)+slider('SSR','Verklaarde kwadratensom SSR',1351.262,0,2000,10)+slider('SSE','Residuele kwadratensom SSE',44.105,1,1000,5),run:(el,v)=>original.anova.run(el,v)+explain('R² is het verklaarde aandeel in SSR + SSE. F vergelijkt de gemiddelde verklaarde kwadratensom met de gemiddelde residuele kwadratensom. Meer variabelen gebruiken vrijheidsgraden; k telt de constante niet mee.')+tryThis('Houd SSR gelijk en verhoog SSE. Bekijk tegelijk R², F en de residuele standaardfout.')};
 configs.toets={...original.toets,fields:slider('p','Tweezijdige p-waarde uit Sig.',.03,0,1,.005)+slider('alpha','Significantieniveau α',.05,.01,.1,.005)+select('direction','Alternatieve hypothese',[['two','β₁ ≠ 0'],['positive','β₁ > 0'],['negative','β₁ < 0']])+select('sign','Teken van de gevonden B',[['positive','Positief'],['negative','Negatief']]),run:(el,v)=>{const base=original.toets.run(el,v),direction=choice(el,'direction'),sign=choice(el,'sign'),p=direction==='two'?v.p:direction===sign?v.p/2:1-v.p/2;return base+graph('Beslissen door p met α te vergelijken',[{name:'Gekozen α',points:[[v.alpha,0],[v.alpha,1]],color:colors[2],dash:true},{name:'p voor H₁',points:[[p,.5]],line:false,radius:8,color:colors[1]}],{xmin:0,xmax:1,ymin:0,ymax:1,xlabel:'Kanswaarde tussen 0 en 1',ylabel:'Vergelijkingslijn',note:'Dit is een beslisschema, geen kansverdeling. Links van α: p < α en H₀ verwerpen. Op of rechts van α: H₀ niet verwerpen. De verticale positie van de stip heeft geen statistische betekenis.'})+explain('Een p-waarde is geen kans dat H₀ waar is. Bij een eenzijdige toets telt ook de richting van B: bij een tegengesteld teken komt de relevante p juist dicht bij 1 te liggen.')+tryThis('Kies H₁: β₁ > 0 en wissel het teken van B van positief naar negatief.');}};
 configs.voorspelling={...original.voorspelling,fields:field('b0','Constante b₀',7.159)+slider('b1','Helling b₁',.099,-.2,.3,.005)+slider('x0','Nieuwe waarde x₀',228.1,100,350,1)+field('xbar','Gemiddelde x̄',228.1)+slider('n','Aantal waarnemingen n',30,3,200,1)+slider('sx','Standaardafwijking x',30,1,100,1)+slider('se','Std. Error of the Estimate',1.25506,0,5,.05)+field('t','Kritieke t bij df = n − 2',2.048,'min="0.0001"'),run:(el,v)=>{
  const r=predictionBands(v),a=v.xbar-120,b=v.xbar+120,xs=seq(a,b,60),pred=xs.map(x=>predictionBands({...v,x0:x})),meanMargin=x=>predictionBands({...v,x0:x}).meanMargin,upper=xs.map((x,i)=>[x,pred[i].high]),lower=xs.map((x,i)=>[x,pred[i].low]);
  const inRange=v.x0>=a&&v.x0<=b;return results([[fmt(r.point,4),'Puntvoorspelling ŷ₀'],[fmt(r.margin,4),'Individuele marge'],[fmt(meanMargin(v.x0),4),'Marge gemiddelde respons']])+graph('Voorspelling en onzekerheidsbanden',[{name:'Individuele bovengrens',points:upper},{name:'Individuele ondergrens',points:lower,color:colors[0]},{name:'Grens gemiddelde respons',points:xs.map((x,i)=>[x,pred[i].point+meanMargin(x)]),color:colors[3],dash:true},{points:xs.map((x,i)=>[x,pred[i].point-meanMargin(x)]),color:colors[3],dash:true},{name:'Regressielijn',points:xs.map((x,i)=>[x,pred[i].point]),color:colors[1]},...(inRange?[{name:'Jouw x₀',points:[[v.x0,r.point]],line:false,color:colors[2],radius:7}]:[])],{xmin:a,xmax:b,band:{high:upper,low:lower},vertical:[v.xbar,...(inRange?[v.x0]:[])],xlabel:'Nieuwe verklarende waarde x₀',ylabel:'Voorspelde y en grenzen',note:'Het getoonde x-gebied blijft x̄ ± 120 als je x₀ verandert. Dit demonstratiegebied is niet het waargenomen databereik. Controleer extrapolatie afzonderlijk. De y-schaal verandert met het model, niet met de geselecteerde x₀.'})+explain(`Bij x₀ = ${fmt(v.x0)} is de afstand tot x̄ ${fmt(Math.abs(v.x0-v.xbar))}. Het individuele interval is [${fmt(r.low)}; ${fmt(r.high)}]. De extra 1 onder de wortel neemt de spreiding van een nieuwe waarneming mee. ${inRange?'':'Je x₀ ligt buiten het getoonde demonstratiegebied; de berekening hierboven blijft zichtbaar.'}`)+dataTable('Twee soorten onzekerheid',['Voorspelling','Ondergrens','Bovengrens'],[['Eén nieuwe waarneming',fixed(r.low),fixed(r.high)],['Gemiddelde respons',fixed(r.point-meanMargin(v.x0)),fixed(r.point+meanMargin(v.x0))]])+tryThis('Schuif x₀ vanaf x̄ naar de rand. Verlaag daarna sₓ: dezelfde afstand telt dan zwaarder mee.');
 }};
 configs.transformatie={...original.transformatie,fields:select('model','Model',[['power','Machtsfunctie (Power)'],['exponential','Exponentieel'],['log','Logaritmisch']])+slider('b0','Constante b₀',1,-3,3,.1)+slider('b1','Coëfficiënt b₁',.5,-1,1,.05)+slider('x','Waarde van x',16,1,30,1),run:(el,v)=>{
  const base=original.transformatie.run(el,v),model=choice(el,'model'),f=x=>{const z=v.b0+v.b1*(model==='exponential'?x:Math.log(x));return model==='log'?z:Math.exp(z);},a=model==='exponential'?0:1,b=30,trans=x=>model==='exponential'?x:Math.log(x),selected=f(v.x),linear=v.b0+v.b1*trans(v.x);
  if(!Number.isFinite(selected))throw Error('Deze voorspelling is te groot.');return base+graph('Het verband op de oorspronkelijke schaal',[{name:'Modelcurve',points:curve(f,a,b,80)},...(v.x>=a&&v.x<=b?[{name:'Jouw invoer',points:[[v.x,selected]],line:false,color:colors[2],radius:7}]:[])],{xlabel:'Oorspronkelijke x',ylabel:'Voorspelde y',note:'Het getoonde x-bereik blijft vast. De y-as past zich aan de gekozen coëfficiënten aan.'})+graph('Na de transformatie: een rechte lijn',[{name:'Lineair geschatte vorm',points:curve(x=>v.b0+v.b1*x,trans(a),trans(b))}],{xlabel:model==='exponential'?'x':'ln(x)',ylabel:model==='log'?'y':'ln(y)'})+explain(`De getransformeerde invoer is ${fmt(trans(v.x),4)} en de lineaire uitkomst ${fmt(linear,4)}. ${model==='log'?'Alleen x is getransformeerd; y blijft op de oorspronkelijke schaal.':'y is logaritmisch gemodelleerd: exp brengt de uitkomst terug op de oorspronkelijke schaal.'}`)+tryThis('Zet b₁ op 0. Beide grafieken worden horizontaal. Kies daarna b₁ < 0 om een dalend verband te zien.');
 }};
 function planning(v){
  requireInteger(v.N,2,'N');requireInteger(v.already,0,'Al gecontroleerd');if(v.already>v.N)throw Error('Het al gecontroleerde aantal mag niet groter zijn dan N.');requirePositive(v.E,'Gewenste marge E');requirePositive(v.t,'Kritieke t');requirePositive(v.sd,'Spreiding');if(Math.abs(v.r)>=1)throw Error('Gebruik −1 < R < 1 voor deze planning; bij perfecte correlatie wordt de planningsvariantie nul.');
  const variance=v.sd*v.sd*(1-v.r*v.r),gamma=v.E*v.E/(v.t*v.t*v.N*variance),raw=v.N/(1+gamma),required=Math.min(v.N,Math.max(2,Math.ceil(raw)));
  if(![variance,gamma,raw].every(Number.isFinite))throw Error('De planningsinvoer is te groot.');return {variance,gamma,raw,required,extra:Math.max(0,required-v.already)};
 }
 function partialF(v){requireInteger(v.n,3,'n');requireInteger(v.k,1,'k uitgebreid');requireInteger(v.q,1,'Aantal toegevoegde variabelen');if(v.n<=v.k+1||v.q>v.k)throw Error('Gebruik n > k + 1 en 1 ≤ q ≤ k.');requirePositive(v.SSRsmall,'SSR klein',true);requirePositive(v.SSRfull,'SSR uitgebreid',true);requirePositive(v.MSE,'MSE uitgebreid');if(v.q===v.k&&v.SSRsmall>1e-10)throw Error('Bij q = k bevat het kleine model alleen de constante; SSR klein moet dan nul zijn.');if(v.SSRfull<v.SSRsmall)throw Error('Bij deze geneste modellen mag SSR uitgebreid niet kleiner zijn dan SSR klein.');return {F:(v.SSRfull-v.SSRsmall)/v.q/v.MSE,df1:v.q,df2:v.n-v.k-1};}
 function validation(actual,pred){if(actual.length!==pred.length||!actual.length||actual.some(x=>!Number.isFinite(x))||pred.some(x=>!Number.isFinite(x)))throw Error('Gebruik even lange, niet-lege reeksen met geldige waarden.');const residuals=actual.map((y,i)=>y-pred[i]),squares=residuals.map(e=>e*e),sum=squares.reduce((a,b)=>a+b,0);if(!Number.isFinite(sum))throw Error('De voorspelfouten zijn te groot.');return {residuals,squares,sum,mspr:sum/actual.length};}
 function collinearity(auxR2){if(!Number.isFinite(auxR2)||auxR2<0||auxR2>=1)throw Error('Gebruik 0 ≤ hulp-R² < 1; bij 1 is VIF niet eindig.');const tolerance=1-auxR2;return {tolerance,vif:1/tolerance,flag:auxR2>.9};}
 function predictionBands(v){const r=M.predict(v),meanMargin=v.t*v.se*Math.sqrt(1/v.n+r.extra);return {...r,meanMargin,meanLow:r.point-meanMargin,meanHigh:r.point+meanMargin};}
 Object.assign(configs,{
  populatie:{title:'Van een paar artikelen naar de hele voorraad',hint:'Deze oefenvoorraad bestaat uit 20 artikelen. De werkelijke waarde is hier zichtbaar zodat je een schatting kunt vergelijken. In de praktijk is het populatietotaal juist onbekend.',fields:slider('n','Hoeveel artikelen controleer je?',5,1,20,1)+select('selection','Welke selectie bekijk je?',[['spread','Vooraf gekozen wisselende selectie'],['cheap','Alleen de goedkoopste artikelen']])+slider('offset','Nummer van de wisselende selectie',0,0,19,1),run:(el,v)=>{
   requireInteger(v.n,1,'n');requireInteger(v.offset,0,'Selectienummer');if(v.n>20||v.offset>19)throw Error('Gebruik n ≤ 20 en selectienummer 0 t/m 19.');const values=[20,25,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,110,120,130],ids=choice(el,'selection')==='cheap'?seq(0,v.n-1,v.n-1||1).slice(0,v.n):Array.from({length:v.n},(_,i)=>(i*7+v.offset)%20),sample=ids.map(i=>values[i]),mean=sample.reduce((a,b)=>a+b,0)/v.n,total=values.reduce((a,b)=>a+b,0),point=20*mean;
   return results([[v.n+' / 20','Steekproef / populatie'],['€ '+fixed(mean),'Steekproefgemiddelde'],['€ '+fixed(point),'Geschat populatietotaal']])+graph('Welke artikelen zitten in de steekproef?',[{name:'Niet geselecteerd',points:values.map((y,i)=>[i+1,y]).filter((p,i)=>!ids.includes(i)),line:false,color:'#9ca6b0'},{name:'Geselecteerd',points:ids.map(i=>[i+1,values[i]]),line:false,color:colors[0],radius:6}],{xmin:0,xmax:21,ymin:0,ymax:140,xlabel:'Artikelnummer',ylabel:'Werkelijke waarde (€)',note:'De wisselende selecties zijn vooraf vastgelegde demonstraties, geen willekeurige trekking. De waarden blijven steeds gelijk.'})+bars('Schatting en hier bekende werkelijkheid',['Schatting','Werkelijk totaal'],[point,total])+explain(`Je telt de geselecteerde waarden op tot € ${fixed(sample.reduce((a,b)=>a+b,0))}, deelt door ${v.n}, en vermenigvuldigt het gemiddelde met N = 20. ${choice(el,'selection')==='cheap'&&v.n<20?'Alleen goedkope artikelen kiezen onderschat hier het totaal. Een grote steekproef herstelt een verkeerde selectie niet vanzelf.':v.n===20?'Bij n = N is het berekende totaal de volledige voorraadwaarde.':'Een andere selectie kan een ander gemiddelde en dus een ander geschat totaal opleveren.'}`)+tryThis('Kies alleen de goedkoopste artikelen. Vergelijk daarna met n = 20.');
  }},
  verschil:{title:'Een vast verschil van de boekwaarde aftrekken',hint:'De fout is e = b − w. Een positieve fout betekent een te hoge boekwaarde. De lijnen tonen dit vaste verschil; de intervalberekening gebruikt de ingevoerde steekproefspreiding.',fields:field('N','Aantal posten N',3740,'min="2" step="1"')+field('n','Gecontroleerde posten n',165,'min="2" step="1"')+field('B','Bekend boekwaardetotaal B (€)',1980000)+slider('meanError','Gemiddeld verschil ē (€)',47,-100,100,1)+slider('sdError','Spreiding van verschillen sₑ (€)',13.6406405,0,100,1)+field('t','Kritieke t',1.975,'min="0.0001"'),run:(el,v)=>{
   const r=M.difference(v),a=0,b=1000;return results([['€ '+fixed(v.N*v.meanError),'Geschatte totale fout'],['€ '+fixed(r.point),'Geschatte werkelijke waarde'],['€ '+fixed(r.margin),'Onzekerheidsmarge']])+graph('Boekwaarde en een constant verschil',[{name:'Zonder verschil: w = b',points:[[a,a],[b,b]],color:'#8c949e',dash:true},{name:'Werkelijk: w = b − ē',points:[[a,a-v.meanError],[b,b-v.meanError]],color:colors[0]}],{xmin:0,xmax:1000,xlabel:'Boekwaarde b (€)',ylabel:'Werkelijke waarde w (€)',note:'Een schematisch verband bij een constant verschil; dit zijn geen nagebootste waarnemingen uit de tentamencasus.'})+explain(`Ŵ = ${fmt(v.B)} − ${fmt(v.N)} × ${fmt(v.meanError)} = € ${fixed(r.point)}. ${v.meanError<0?'Een negatief verschil wordt afgetrokken: de schatting komt dus boven de boekwaarde uit.':v.meanError===0?'Zonder gemiddeld verschil is de puntschatting gelijk aan B.':'Een positief verschil wordt van de boekwaarde afgetrokken.'} Het interval is [€ ${fixed(r.low)}; € ${fixed(r.high)}]. De cursusvoorwaarde van minstens 30 afwijkende posten moet je afzonderlijk controleren.`)+dataTable('Berekening',['Onderdeel','Waarde'],[['B',fixed(v.B)],['N × ē',fixed(v.N*v.meanError)],['Standaardfout',fixed(r.se)],['Ondergrens',fixed(r.low)],['Bovengrens',fixed(r.high)]])+tryThis('Verander ē van +47 naar −47. De richting van de correctie keert om, de marge blijft gelijk.');
  }},
  quotient:{title:'Een vaste verhouding tussen boekwaarde en werkelijke waarde',hint:'De goedratio q is de verhouding van twee sommen. De lijn gaat door de oorsprong: bij een vaste verhouding verandert het verschil in euro’s mee met de boekwaarde.',fields:field('N','Aantal posten N',1000,'min="2" step="1"')+field('n','Steekproefomvang n',100,'min="2" step="1"')+field('B','Boekwaardetotaal B (€)',500000)+slider('sumW','Som werkelijke waarden Σw (€)',19000,10000,25000,100)+field('sumB','Som boekwaarden Σb (€)',20000)+field('sw','Spreiding s_w (€)',38,'min="0"')+field('sb','Spreiding s_b (€)',40,'min="0"')+slider('r','Correlatie R_bw',.98,-1,1,.01)+field('t','Kritieke t',1.987,'min="0.0001"'),run:(el,v)=>{
   const r=M.ratio(v);return results([[fmt(r.q,4),'Goedratio q'],['€ '+fixed(r.point),'Geschat totaal'],['€ '+fixed(r.sq),'Resterende spreiding s_q']])+graph('De verhouding bepaalt de helling',[{name:'Boekwaarde = werkelijk',points:[[0,0],[1000,1000]],color:'#9098a0',dash:true},{name:'w = q × b',points:[[0,0],[1000,1000*r.q]],color:colors[0]}],{xmin:0,xmax:1000,xlabel:'Boekwaarde b (€)',ylabel:'Werkelijke waarde w (€)',note:'De groene lijn is de schematische verhouding. R_bw en de spreidingen worden apart gebruikt voor de onzekerheid; de lijn is geen getekende steekproef.'})+dataTable('Hetzelfde percentage bij verschillende posten',['Boekwaarde','Geschatte werkelijke waarde','Verschil'],[100,200,500,1000].map(b=>[fixed(b),fixed(r.q*b),fixed(b-r.q*b)]))+explain(`q = ${fmt(v.sumW)} / ${fmt(v.sumB)} = ${fmt(r.q,4)}. Dit levert een interval van € ${fixed(r.low)} tot € ${fixed(r.high)}. De verhouding van sommen is niet in het algemeen gelijk aan het gemiddelde van losse verhoudingen. Controleer ook hier de cursusvoorwaarde van minstens 30 fouten.`)+tryThis('Verlaag Σw en bekijk de helling. Verlaag daarna alleen de correlatie: de puntschatting blijft gelijk, de marge verandert.');
  }},
  regressieschatter:{title:'Corrigeren met bekende boekwaarden',hint:'Begin bij MPU. Corrigeer het verschil tussen de boekwaarde uit de steekproef en het bekende boekwaardetotaal. De correlatie bepaalt ook hoeveel onzekerheid overblijft.',fields:field('N','Aantal posten N',2130,'min="2" step="1"')+field('n','Steekproefomvang n',180,'min="2" step="1"')+field('B','Bekend boekwaardetotaal B (€)',1810500)+field('mw','Gemiddelde werkelijke waarde w̄',161300/180)+slider('mb','Gemiddelde boekwaarde b̄',164500/180,700,1100,1)+field('sw','Spreiding s_w',82.1,'min="0"')+field('sb','Spreiding s_b',83.3,'min="0.0001"')+slider('r','Correlatie R_bw',.925,-1,1,.005)+field('t','Kritieke t',1.974,'min="0.0001"'),run:(el,v)=>{
   const r=M.regressionEstimator(v),mpu=M.estimate({N:v.N,n:v.n,mean:v.mw,sd:v.sw,t:v.t}),populationMean=v.B/v.N,lo=Math.min(v.mb,populationMean)-100,hi=Math.max(v.mb,populationMean)+100,f=x=>v.mw+r.b1*(x-v.mb);
   return results([['€ '+fixed(r.point),'Regressieschatter'],['€ '+fixed(mpu.point),'MPU vóór correctie'],[fmt(Math.sqrt(1-v.r*v.r),4),'Factor standaardfout']])+graph('Van steekproefgemiddelde naar populatiegemiddelde',[{name:'Correctielijn',points:curve(f,lo,hi)},{name:'Steekproef (b̄, w̄)',points:[[v.mb,v.mw]],line:false,color:colors[1],radius:7},{name:'Bekende B/N, gecorrigeerde waarde',points:[[populationMean,r.point/v.N]],line:false,color:colors[2],radius:7}],{xlabel:'Gemiddelde boekwaarde per post (€)',ylabel:'Geschatte werkelijke waarde per post (€)'})+bars('Vergelijk de standaardfouten',['MPU','Regressieschatter'],[mpu.se,r.se])+explain(`b₁ = ${fmt(v.r,3)} × ${fmt(v.sw)} / ${fmt(v.sb)} = ${fmt(r.b1,5)}. De correctie is € ${fixed(r.point-mpu.point)}. Het interval is [€ ${fixed(r.low)}; € ${fixed(r.high)}]. Bij R = 0 vervalt de correctie en is er geen vermindering van de standaardfout.`)+tryThis('Zet R op 0 en daarna op 0,8. Bij 0,8 blijft 60% van de MPU-standaardfout over.');
  }},
  omvang:{title:'Hoeveel controles vraagt jouw gewenste precisie?',hint:'Gebruik de planningsformule van het formuleblad. E is de halve intervalbreedte. Voor MPU of verschil vul je de passende spreiding in en zet je R op 0; voor de regressieschatter gebruik je R_bw.',fields:field('N','Aantal posten N',2130,'min="2" step="1"')+slider('E','Gewenste marge E (€)',5000,1000,20000,100)+slider('sd','Passende spreiding s',82.1,1,150,1)+slider('r','R (0 bij MPU of verschil)',.925,-.99,.99,.005)+field('t','Kritieke t voor de planning',1.974,'min="0.0001"')+field('already','Al gecontroleerde posten',180,'min="0" step="1"'),run:(el,v)=>{
   const r=planning(v),points=seq(1000,20000,75).map(E=>[E,planning({...v,E}).required]);return results([[fmt(r.raw,3),'Uitkomst vóór afronden'],[r.required,'Totale vereiste omvang'],[r.extra,'Nog te controleren']])+graph('Meer precisie vraagt meer controles',[{name:'Naar boven afgeronde omvang',points},...(v.E>=1000&&v.E<=20000?[{name:'Jouw keuze',points:[[v.E,r.required]],line:false,color:colors[2],radius:7}]:[])],{xmin:1000,xmax:20000,ymin:0,ymax:v.N,xlabel:'Toegestane marge E (€)',ylabel:'Benodigde steekproefomvang n',note:'Vast bereik van € 1.000 tot € 20.000. Dit is de cursusplanningsformule met vaste t, niet de exacte algebraïsche inverse van de intervalformule met N − 1.'})+line(`s²_eff = ${fmt(r.variance,5)}; γ = ${fmt(r.gamma,5)}; n = ${v.N} / (1 + ${fmt(r.gamma,5)}) = ${fmt(r.raw,5)}.`)+explain(`Rond de vereiste omvang naar boven af. ${r.raw<2?'Deze invoer levert minder dan twee posten op; het werkblad houdt minimaal twee aan om een steekproefspreiding te kunnen gebruiken. ':''}${v.already>=r.required?'Het reeds gecontroleerde aantal is minstens de berekende vereiste omvang.':`Na ${v.already} controles heb je er nog ${r.extra} nodig.`} Bij perfecte correlatie of nulspreiding levert deze planningsroute geen bruikbare onzekerheidsinschatting; die invoer wordt apart gemeld.`)+tryThis('Verlaag E van € 5.000 naar € 2.500. Je vraagt een smaller interval en moet meer controleren.');
  }},
  meervoudig:{title:'Verander één kenmerk en houd de andere gelijk',hint:'Een vereenvoudigd salarisvoorbeeld met leeftijd, beoordelingsscore en een dummy voor leidinggeven. De startcoëfficiënten komen uit de besproken tentamencasus; de getekende lijnen illustreren het model.',fields:slider('age','Leeftijd',50,18,70,1)+slider('rating','Beoordelingsscore (demo-bereik)',10,0,10,.5)+select('group','Leidinggevende',[['0','Nee: dummy = 0'],['1','Ja: dummy = 1']])+field('b0','Constante b₀',739.508)+slider('bAge','Coëfficiënt leeftijd',38.495,-50,100,.5)+slider('bRating','Coëfficiënt beoordeling',71.55,-100,150,.5)+slider('bDummy','Coëfficiënt leidinggevende',2237.947,-3000,3000,50),run:(el,v)=>{
   if(v.age<0||v.rating<0)throw Error('Gebruik geen negatieve leeftijd of beoordelingsscore.');const d=Number(choice(el,'group')),f=(x,g)=>v.b0+v.bAge*x+v.bRating*v.rating+v.bDummy*g,point=f(v.age,d);return results([['€ '+fixed(point),'Voorspeld salaris'],['€ '+fixed(v.bAge),'Effect van +1 jaar leeftijd'],['€ '+fixed(v.bDummy),'Groepsverschil bij gelijke kenmerken']])+graph('Twee groepen bij dezelfde beoordeling',[{name:'Geen leidinggevende (0)',points:curve(x=>f(x,0),18,70)},{name:'Leidinggevende (1)',points:curve(x=>f(x,1),18,70),color:colors[3]},...(v.age>=18&&v.age<=70?[{name:'Jouw persoon',points:[[v.age,point]],line:false,color:colors[2],radius:7}]:[])],{xmin:18,xmax:70,xlabel:'Leeftijd (jaren)',ylabel:'Voorspeld salaris (€)',note:`Beoordeling staat vast op ${fmt(v.rating)} punten. Parallelle lijnen: dit model bevat geen interactieterm. Het diagram is een modelillustratie, geen bewijs van causaliteit.`})+dataTable('Zo wordt de voorspelling opgebouwd',['Term','Bijdrage (€)'],[['Constante',fixed(v.b0)],['Leeftijd × coëfficiënt',fixed(v.age*v.bAge)],['Beoordeling × coëfficiënt',fixed(v.rating*v.bRating)],['Dummy × coëfficiënt',fixed(d*v.bDummy)]],['Samen',fixed(point)])+explain('De leeftijdscoëfficiënt geldt bij gelijkblijvende beoordeling en groep. Het wijzigen van de beoordeling verschuift beide lijnen. Het wijzigen van de dummycoëfficiënt verandert hun onderlinge afstand.')+tryThis('Zet de dummycoëfficiënt op nul. De groepslijnen vallen samen. Maak daarna de leeftijdscoëfficiënt negatief.');
  }},
  modelbouw:{title:'Overlap en de bijdrage van extra variabelen',hint:'Onderzoek VIF met de R² uit een hulpregressie. Vergelijk daarnaast twee geneste modellen met dezelfde y en dezelfde waarnemingen. De voorbeelden zijn afzonderlijke rekenexperimenten.',fields:slider('auxR2','Hulpregressie R²ᵢ',.92,0,.99,.01)+field('n','Aantal waarnemingen n',100,'min="3" step="1"')+field('k','k in het uitgebreide model',3,'min="1" step="1"')+slider('q','Aantal toegevoegde variabelen q',1,1,3,1)+field('SSRsmall','SSR klein model',800,'min="0"')+slider('SSRfull','SSR uitgebreid model',850,800,1000,5)+field('MSE','MSE uitgebreid model',10,'min="0.0001"'),run:(el,v)=>{
   const {tolerance,vif,flag}=collinearity(v.auxR2),r=partialF(v);return results([[fmt(tolerance,4),'Tolerance'],[fmt(vif,3),'VIF'],[fmt(r.F,4),'F voor de extra bijdrage']])+graph('Sterkere overlap vergroot VIF',[{name:'VIF = 1 / (1 − R²ᵢ)',points:curve(x=>1/(1-x),0,.98,98)},{name:'Jouw hulp-R²',points:[[v.auxR2,vif]],line:false,color:colors[2],radius:7}],{xmin:0,xmax:1,ymin:0,ymax:Math.max(50,vif*1.1),horiz:[10],xlabel:'R²ᵢ van de hulpregressie',ylabel:'Variance Inflation Factor',note:'De stippellijn is de cursusgrens VIF = 10. De hoofdmodel-R² hoort niet in deze formule.'})+explain(`${flag?'VIF overschrijdt 10: onderzoek welke verklarende variabelen sterk overlappen.':'VIF overschrijdt de cursusgrens 10 niet.'} De extra bijdrage is F = [(${fmt(v.SSRfull)} − ${fmt(v.SSRsmall)}) / ${v.q}] / ${fmt(v.MSE)} = ${fmt(r.F,4)} met (${r.df1}, ${r.df2}) vrijheidsgraden. Zonder α en de bijpassende grens kun je hier nog geen significantiebeslissing nemen.`)+dataTable('Geneste modellen vergelijken',['Onderdeel','Waarde'],[['Extra SSR',fixed(v.SSRfull-v.SSRsmall)],['Aantal extra variabelen',v.q],['MSE uitgebreid',fixed(v.MSE)],['F',fixed(r.F,4)],['Vrijheidsgraden teller / noemer',r.df1+' / '+r.df2]])+tryThis('Vergelijk hulp-R² = 0,5, 0,9 en 0,95. Verhoog daarna q bij dezelfde extra SSR: per extra variabele is de bijdrage kleiner.');
  }},
  validatie:{title:'Een vast model toetsen op nieuwe waarnemingen',hint:'De voorspellingen van dit al getrainde model blijven 12, 13 en 17. Verander alleen de nieuwe werkelijke uitkomsten en vergelijk MSPR met de opgegeven MSE van de trainingsset.',fields:slider('y1','Werkelijke testuitkomst 1',10,0,30,1)+slider('y2','Werkelijke testuitkomst 2',14,0,30,1)+slider('y3','Werkelijke testuitkomst 3',20,0,30,1)+field('trainMSE','MSE van de trainingsset',4.5,'min="0"'),run:(el,v)=>{
   requirePositive(v.trainMSE,'Trainings-MSE',true);const actual=[v.y1,v.y2,v.y3],pred=[12,13,17],r=validation(actual,pred);return results([[fmt(r.mspr,4),'MSPR op drie nieuwe waarnemingen'],[fmt(v.trainMSE,4),'MSE van trainingsset'],[fmt(r.sum,3),'Som gekwadrateerde testfouten']])+graph('Vaste voorspellingen en nieuwe uitkomsten',[{name:'Voorspelling uit trainingsmodel',points:pred.map((y,i)=>[i+1,y]),dots:true},{name:'Werkelijke testuitkomst',points:actual.map((y,i)=>[i+1,y]),line:false,color:colors[2],radius:6},...actual.map((y,i)=>({points:[[i+1,pred[i]],[i+1,y]],color:'#aaa3ad',dash:true}))],{xmin:.5,xmax:3.5,ymin:Math.min(0,...actual),ymax:Math.max(32,...actual),xlabel:'Testwaarneming',ylabel:'Waarde y',note:'Een verandering in de testset leidt hier niet tot opnieuw trainen. Zo blijven de testgegevens buiten de schatting van het model.'})+dataTable('MSPR stap voor stap',['Waarneming','Werkelijk y','Voorspeld ŷ','Fout y − ŷ','Fout²'],actual.map((y,i)=>[i+1,fixed(y),fixed(pred[i]),fixed(r.residuals[i]),fixed(r.squares[i])]),['Som','','','',fixed(r.sum)])+explain(`MSPR = ${fmt(r.sum)} / 3 = ${fmt(r.mspr,4)}. Je deelt door het aantal testwaarnemingen, niet door n − k − 1. Vergelijk dit met trainings-MSE ${fmt(v.trainMSE)}. De cursus geeft geen universele grens voor “ongeveer gelijk”; een duidelijk grotere testfout vraagt onderzoek naar generalisatie.`)+tryThis('Vul als werkelijke uitkomsten 12, 13 en 17 in. MSPR wordt nul; de voorspellingen veranderen niet.');
  }},
  keuzeroute:{title:'Kies de methode vanuit de vraag',hint:'Verander het doel en het beschreven patroon. Het schema laat zien welke gegevens, berekening en controle bij die keuze horen. Het is een oefenroute, geen automatische beoordeling van een echte casus.',fields:select('goal','Wat wordt gevraagd?',[['total','Een populatietotaal schatten'],['prediction','Een nieuwe y voorspellen'],['test','Een regressiecoëfficiënt toetsen'],['size','De benodigde steekproefomvang']])+select('pattern','Welk patroon of gegeven is beschikbaar?',[['none','Alleen werkelijke steekproefwaarden'],['difference','Boekwaarden en ongeveer constante fouten'],['ratio','Boekwaarden en ongeveer vaste verhouding'],['regression','Bekende B en een passend lineair verband']]),run:(el)=>{
   const goal=choice(el,'goal'),pattern=choice(el,'pattern'),methods={none:['MPU','N, n, w̄, s_w en kritieke t','Ŵ = N × w̄','mpu'],difference:['Verschilschatter','B, N, n, ē, s_e en kritieke t','Ŵ = B − N × ē','verschil'],ratio:['Quotiëntschatter','B, Σw, Σb en de passende spreidingsgegevens','q = Σw / Σb; Ŵ = q × B','quotient'],regression:['Regressieschatter','B, N, n, gemiddelden, spreidingen en correlatie','Ŵ = Nw̄ + b₁(B − Nb̄)','regressieschatter']};let selected=methods[pattern],checks='Bereken daarna de standaardfout en het interval. Controleer bronvoorwaarden en rond grenzen naar buiten af wanneer dat wordt gevraagd.';
   if(goal==='prediction'){selected=['Individueel voorspellingsinterval','Regressiemodel, x₀, n, x̄, s_x, s_e en t','Eerst ŷ₀, daarna de marge met de extra 1','voorspellen'];checks='Controleer modelaannames, eenheden en het oorspronkelijke x-bereik. Eén nieuwe waarneming is iets anders dan een gemiddelde respons.';}
   if(goal==='test'){selected=['t-toets van één coëfficiënt','B, Std. Error, df, α en vooraf gekozen H₁','t = B / Std. Error; gebruik de passende toetsrichting','toetsen'];checks='Formuleer H₀ en H₁. Lees een tweezijdige Sig. zorgvuldig als de vraag eenzijdig is. Een niet-significante uitkomst bewijst H₀ niet.';}
   if(goal==='size'){selected=['Planningsformule voor n','N, halve intervalbreedte E, passende variantie en t','Bereken γ, dan n; rond n naar boven af','steekproefomvang'];checks='Gebruik de spreiding die bij de schatter hoort. Trek reeds gecontroleerde posten af als de uitbreiding wordt gevraagd.';}
   return `<ol class="lab-route"><li><span>1 · Methode</span><strong>${esc(selected[0])}</strong></li><li><span>2 · Benodigde gegevens</span>${esc(selected[1])}</li><li><span>3 · Berekening</span>${esc(selected[2])}</li><li><span>4 · Controle en conclusie</span>${esc(checks)}</li></ol>`+explain(goal==='total'&&(pattern==='difference'||pattern==='ratio')?'Controleer bij deze cursusmethoden ook of minstens 30 afwijkende posten zijn gevonden. Een passend patroon alleen is niet voldoende.':'Schrijf bij je uitkomst altijd wat deze betekent in de casus. De keuze begint bij het gevraagde doel, niet bij een toevallig bekende formule.')+`<a class="btn small" href="#les/${selected[3]}">Open de bijbehorende les</a>`;
  }}
 });
 const modeFields=(modes,html)=>`<div class="lab-mode-fields" data-modes="${modes}">${html}</div>`;
 configs.diagnose={title:'Herken het patroon achter een diagnose',hint:'Kies een afbeelding of grenscontrole. De punten zijn vaste didactische voorbeelden: een zichtbaar patroon is een onderzoekssignaal. Een tabeltoets en inhoudelijke verklaring blijven nodig.',fields:select('mode','Onderzoek',[['residual','Residuendiagram'],['normal','Normaliteitsplot en histogram'],['outlier','Uitbijter in y'],['distance','Mahalanobis en Cook'],['dw','Durbin-Watson bij een tijdreeks']])+modeFields('residual',select('pattern','Patroon in de residuen',[['spread','Constante spreiding'],['funnel','Trechter: veranderende spreiding'],['curve','Kromming: niet passend recht verband'],['time','Opeenvolgende tijdpatronen']])+slider('strength','Sterkte van het patroon',1,0,3,.1))+modeFields('normal',slider('skew','Afwijking van de symmetrische vorm',0,0,2,.1))+modeFields('normal outlier',field('n','Aantal waarnemingen n',100,'min="3" step="1"'))+modeFields('outlier',slider('z','Gestandaardiseerd residu z',2.5,-5,5,.1))+modeFields('distance',select('distance','Soort afstand',[['md','Mahalanobis Distance: uitbijter in x'],['cd','Cook’s Distance: invloedrijk punt']])+field('average','Gemiddelde afstand',.967,'min="0"')+field('distanceSD','Standaardafwijking afstand',1.112,'min="0"')+slider('maximum','Maximumafstand',4.245,0,8,.05))+modeFields('dw',slider('d','Durbin-Watson d',2,0,4,.05)+field('dL','Tabelgrens dL',1.35)+field('dU','Tabelgrens dU',1.49)),run:(el,v)=>{
  const mode=choice(el,'mode');
  if(mode==='residual'){
   requirePositive(v.strength,'Patroonsterkte',true);if(v.strength>3)throw Error('Gebruik een patroonsterkte tussen 0 en 3.');const pattern=choice(el,'pattern'),noise=[-.8,.6,-.3,.9,-.6,.2,.7,-.9,.4,-.2,.8,-.5],ys=noise.map((e,i)=>pattern==='funnel'?e*(.4+v.strength*i/3):pattern==='curve'?e+v.strength*((i-5.5)**2/10-1.2):pattern==='time'?e*.25+v.strength*1.5*Math.sin(i/2):e*(.5+v.strength*.5)),points=ys.map((y,i)=>[i+1,y]),meaning={spread:'De punten liggen zonder duidelijk systematisch patroon rond nul. Dit ondersteunt een constante spreiding, maar bewijst die aanname niet.',funnel:'De waaier wordt breder: de residuele spreiding verandert met x. Dit is een signaal van heteroscedasticiteit. Onderzoek een passende modelaanpassing of weging.',curve:'De punten vormen een boog. Een rechte lijn mist hier een deel van de structuur; onderzoek een passende modelvorm.',time:'Opeenvolgende residuen bewegen samen in golven. Bij tijdreeksgegevens is dit een signaal om autocorrelatie te onderzoeken.'};
   return graph('Residuen: wat blijft er na het model over?',[{name:'Residuen',points,line:pattern==='time',dots:true}],{xmin:0,xmax:13,ymin:-12,ymax:12,horiz:[0],xlabel:pattern==='time'?'Volgorde in de tijd':'Verklarende waarde x (demo)',ylabel:'Residu y − ŷ',note:'Vaste schaal van −12 tot +12 om patronen te vergelijken. Dit zijn schematische residuen, geen berekende toetsuitslag.'})+explain(v.strength===0&&pattern!=='spread'?'De patroonsterkte staat op nul: alleen de vaste achtergrondresiduen blijven over. Vergroot de sterkte om het gekozen patroon zichtbaar te maken.':meaning[pattern])+details('Lees de getekende waarden',dataTable('Residuen',['Positie','Residu'],ys.map((y,i)=>[i+1,fixed(y,3)])))+tryThis('Vergelijk constante spreiding met de trechter. Verander de patroonsterkte terwijl de assen gelijk blijven.');
  }
  if(mode==='normal'){
   requireInteger(v.n,3,'n');if(v.skew<0||v.skew>3)throw Error('Gebruik een vormafwijking tussen 0 en 3.');const q=[-1.732,-1.15,-.812,-.549,-.319,-.105,.105,.319,.549,.812,1.15,1.732],raw=q.map(x=>x+v.skew*(Math.exp(x*.65)-1-x*.65)),center=raw.reduce((a,b)=>a+b,0)/raw.length,ys=raw.map(y=>y-center).sort((a,b)=>a-b),edges=[-4,-3,-2,-1,0,1,2,3,4,5,6],counts=edges.slice(0,-1).map((a,i)=>ys.filter(y=>y>=a&&(i===edges.length-2?y<=edges[i+1]:y<edges[i+1])).length);
   return graph('Q-Q-plot: residuen tegenover een normaalreferentie',[{name:'Normaalreferentie y = x',points:[[-2,-2],[2,2]],color:'#848c95',dash:true},{name:'Geordende demo-residuen',points:q.map((x,i)=>[x,ys[i]]),line:false,color:colors[0],radius:5}],{xmin:-2,xmax:2,xlabel:'Theoretische normale kwantielen (benaderd)',ylabel:'Geordende residuen',note:'Een Q-Q-plot vergelijkt overeenkomstige posities in twee verdelingen. De 12 vaste referentiepunten zijn een tekenvoorbeeld, geen steekproef van omvang n. Dit diagram berekent geen p-waarde.'})+histogram(edges,counts)+explain(`Een ongeveer rechte puntenrij past bij de referentieverdeling. Kromming wijst op een andere vorm. Bij jouw ingestelde n = ${v.n} gebruikt de cursus ${v.n<=50?'Shapiro-Wilk':'Kolmogorov-Smirnov'} om normaliteit van de residuen te toetsen. Het getoonde histogram en de Q-Q-plot zijn alleen een illustratie van de vorm.`)+tryThis('Vergroot de vormafwijking. Bekijk tegelijk de kromming in de Q-Q-plot en de scheefheid in het histogram.');
  }
  if(mode==='outlier'){
   requireInteger(v.n,3,'n');const b=v.n<=100?2:3,flag=Math.abs(v.z)>b;return results([[`−${b} en +${b}`,'Cursusgrenzen'],[fmt(v.z),'Gestandaardiseerd residu'],[flag?'Onderzoeken':'Binnen grenzen','Signaal']])+graph('Ligt het residu buiten de grenzen?',[{name:'Jouw residu',points:[[1,v.z]],line:false,color:flag?colors[2]:colors[0],radius:8}],{xmin:0,xmax:2,ymin:Math.min(-5,v.z-.5),ymax:Math.max(5,v.z+.5),horiz:[-b,0,b],xlabel:'Eén onderzochte waarneming',ylabel:'Gestandaardiseerd residu z',note:`De grenzen zijn ±${b}; alleen |z| > ${b} overschrijdt de cursusgrens.`})+explain(flag?'Onderzoek de waarneming en haar oorzaak. Een grensoverschrijding is geen opdracht om valide data te verwijderen.':'Dit residu overschrijdt de cursusgrens niet. Andere modelproblemen zijn daarmee niet uitgesloten.')+tryThis('Laat z = 2,5 staan en verander n van 100 naar 101. De cursusgrens verandert van 2 naar 3.');
  }
  if(mode==='distance'){
   requirePositive(v.average,'Gemiddelde',true);requirePositive(v.distanceSD,'Standaardafwijking',true);requirePositive(v.maximum,'Maximum',true);if(v.maximum<v.average)throw Error('Het maximum kan niet kleiner zijn dan het gemiddelde.');const bound=v.average+3*v.distanceSD,type=choice(el,'distance')==='md'?'Mahalanobis Distance':'Cook’s Distance';return results([[fmt(bound,4),'Grens: gemiddelde + 3s'],[fmt(v.maximum,4),'Waargenomen maximum'],[v.maximum>bound?'Onderzoeken':'Geen overschrijding','Signaal']])+bars(type+': maximum en grens',['Maximum','Cursusgrens'],[v.maximum,bound])+explain(`${type}: ${fmt(v.average)} + 3 × ${fmt(v.distanceSD)} = ${fmt(bound,4)}. ${choice(el,'distance')==='md'?'MD gaat over een ongebruikelijke positie in de verklarende variabelen.':'CD gaat over hoeveel invloed een waarneming op de regressie heeft.'} Gebruik bij iedere afstand de eigen tabelwaarden. Een signaal vraagt een inhoudelijk onderzoek.`);
  }
  if(v.d<0||v.d>4||v.dL<=0||v.dL>v.dU||v.dU>=2)throw Error('Gebruik 0 ≤ d ≤ 4 en tabelgrenzen 0 < dL ≤ dU < 2.');
  const verdict=v.d<=v.dL?'Aanwijzing voor positieve autocorrelatie':v.d>=4-v.dL?'Aanwijzing voor negatieve autocorrelatie':v.d>=v.dU&&v.d<=4-v.dU?'Geen autocorrelatie aangetoond':'Onbeslist gebied',regions=[['Positief',0,v.dL],['Onbeslist',v.dL,v.dU],['Niet aangetoond',v.dU,4-v.dU],['Onbeslist',4-v.dU,4-v.dL],['Negatief',4-v.dL,4]];
  return results([[fmt(v.d),'Durbin-Watson d'],[verdict,'Beoordeling']])+graph('De vijf gebieden van Durbin-Watson',[...regions.map((r,i)=>({name:r[0],points:[[r[1],.5],[r[2],.5]],color:['#c85209','#d3a048','#008859','#d3a048','#c85209'][i],width:12})),{name:'Jouw d',points:[[v.d,.75]],line:false,color:colors[1],radius:7}],{xmin:0,xmax:4,ymin:0,ymax:1,vertical:[v.dL,v.dU,4-v.dU,4-v.dL],xlabel:'Durbin-Watson d',ylabel:'Beslisgebieden (schematisch)',note:'Zoek dL en dU in de tabellenbundel bij jouw n en k. De ingevulde grenzen zijn een oefenvoorbeeld; de verticale positie heeft geen statistische betekenis.'})+dataTable('Gebieden',['Gebied','Van','Tot'],regions.map(r=>[r[0],fixed(r[1]),fixed(r[2])]))+explain(`d = ${fmt(v.d)}: ${verdict.toLowerCase()}. De exacte grensconventie volgt de les: d ≤ dL en d ≥ 4 − dL geven een aanwijzing; van dU tot 4 − dU wordt geen autocorrelatie aangetoond.`);
 }};
 const intervalRun=configs.interval.run;
 configs.interval.fields+=slider('confidence','Betrouwbaarheid voor het staartschema (%)',95,80,99,.5);
 configs.interval.hint+=' De betrouwbaarheidskeuze hieronder verandert alleen het staartschema: vul de bijpassende t zelf in.';
 configs.interval.run=(el,v)=>{if(v.confidence<=0||v.confidence>=100)throw Error('Gebruik een betrouwbaarheid tussen 0% en 100%.');const alpha=100-v.confidence;return intervalRun(el,v)+`<figure class="chart-figure"><figcaption>Betrouwbaarheid en de twee staarten</figcaption><div class="lab-tail-schema" role="img" aria-label="${fmt(alpha/2)} procent linkerstaart, ${fmt(v.confidence)} procent middengebied en ${fmt(alpha/2)} procent rechterstaart"><span style="flex:${alpha/2}" class="tail"></span><span style="flex:${v.confidence}" class="middle"></span><span style="flex:${alpha/2}" class="tail"></span></div><div class="lab-tail-labels"><span>Links: α/2 = ${fmt(alpha/2)}%</span><strong>Midden: ${fmt(v.confidence)}%</strong><span>Rechts: α/2 = ${fmt(alpha/2)}%</span></div><p class="chart-note">Een kansschema, geen dichtheidskromme. Het centrale aandeel is 1 − α. Zoek t bij deze betrouwbaarheid en df = n − 1; de tool koppelt de gekozen betrouwbaarheid niet automatisch aan de ingevoerde t.</p></figure>`;};
 let resizeObserver;
 function mount(id,container){if(resizeObserver)resizeObserver.disconnect();const c=configs[id];if(!c)return;container.innerHTML=`<div class="block-label">Zelf onderzoeken</div><h2>${c.title}</h2><p>${c.hint}</p><div class="lab-grid">${c.fields}</div><div class="lab-result" aria-live="polite"></div>`;
  const update=()=>{try{const mode=container.querySelector('[name="mode"]')?.value;container.querySelectorAll('[data-modes]').forEach(group=>group.hidden=!group.dataset.modes.split(' ').includes(mode));const values={};container.querySelectorAll('input[type=number][name]').forEach(input=>{if(input.closest('[hidden]'))return;if(input.value.trim()==='')throw Error('Vul alle getalvelden in.');values[input.name]=Number(input.value);if(!Number.isFinite(values[input.name]))throw Error('Vul geldige getallen in.');});container.querySelectorAll('[data-sync]').forEach(range=>{const number=container.querySelector(`[name="${range.dataset.sync}"]`);if(number&&number.value!==''){range.value=number.value;range.setAttribute('aria-valuetext',fmt(Number(range.value),5));}});const html=c.run(container,values);if(/NaN|Infinity|∞/.test(html))throw Error('De invoer levert een te grote of ongedefinieerde uitkomst op. Kies andere waarden.');container.querySelector('.lab-result').innerHTML=html;}catch(error){container.querySelector('.lab-result').innerHTML=`<div class="lab-error" role="status">${esc(error.message)}</div>`;}};
  const handleInput=e=>{if(e.target.matches('[data-sync]')){const number=container.querySelector(`[name="${e.target.dataset.sync}"]`);number.value=e.target.value;}update();};container.addEventListener('input',handleInput);container.addEventListener('change',handleInput);
  const fitButton=container.querySelector('#lab-fit');if(fitButton)fitButton.addEventListener('click',()=>{const fit=M.ols([1,2,3,4,5,6,7,8],[9,10,15,15,21,21,26,27]);for(const key of ['b0','b1']){const slider=container.querySelector(`[name=${key}]`);slider.step='any';slider.value=fit[key];}update();});update();
  let previousWidth=container.clientWidth;resizeObserver=new ResizeObserver(()=>{if(!container.isConnected){resizeObserver.disconnect();return;}if(container.clientWidth!==previousWidth){previousWidth=container.clientWidth;update();}});resizeObserver.observe(container);
 }
 window.SRALabs={mount,ids:Object.keys(configs),calculations:{planning,partialF,validation,collinearity,predictionBands}};
})();
