const assert = require('node:assert/strict'), fs = require('node:fs'), vm = require('node:vm');
const {JSDOM} = require(process.env.JSDOM_PATH || 'jsdom');
const dom = new JSDOM('<!doctype html><html><head><style>html{font-size:14px}.pane{height:calc(100dvh - 110px)!important;max-width:90vw}.card{padding:24px}@media(max-width:680px){.pane{height:45dvh}}</style></head><body><button data-font="-1">A−</button><button data-font="0">A</button><button data-font="1">A+</button></body></html>', {runScripts:'outside-only'});
const {window} = dom;
window.eval(fs.readFileSync('js/page-scale.js','utf8'));
const api=window.StudyScale, pane=window.document.styleSheets[0].cssRules[1];
assert.equal(api.set(10,14,10,24),10);
assert.equal(api.get(),10/14);
assert.equal(window.document.documentElement.style.zoom,String(10/14));
assert.match(pane.style.height,/100dvh \/ var\(--study-page-scale, 1\)/);
assert.equal(pane.style.getPropertyPriority('height'),'important');
assert.equal(window.document.styleSheets[0].cssRules[2].style.padding,'24px','Fixed dimensions are scaled once by root zoom.');
assert.equal(window.document.styleSheets[0].cssRules[3].conditionText,'(max-width:680px)','Responsive breakpoints are preserved.');
assert.ok(window.document.querySelector('[data-font="-1"]').disabled);
const first=pane.style.height;
api.set(24,14,10,24);api.set(18,14,10,24);
assert.equal(pane.style.height,first,'Repeated changes do not compound viewport compensation.');
assert.equal(api.set(100,14,10,24),24);
assert.ok(window.document.querySelector('[data-font="1"]').disabled);
api.set(14,14,10,24);
assert.equal(api.get(),1);
assert.ok(window.document.querySelector('[data-font="0"]').hidden);
assert.match(window.document.querySelector('[data-font="1"]').title,/100%/);
api.set(10,16,10,24);assert.equal(api.get(),.625,'Lessons can shrink sufficiently to fit more content.');
assert.match(window.document.querySelector('[data-font="-1"]').getAttribute('aria-label'),/Hele pagina/);
dom.window.close();
console.log('Paginagrootte: grenzen, herstel, volledige schaal, venstercompensatie, CSS-prioriteit en herhaald wijzigen geslaagd.');
