"""Gemaakt met Codex: MC-leerlijnen uit de bestaande SRA-lesstof, geen officiële examenvragen."""
import json
from pathlib import Path
import build_content as C
from question_explanations import APPLICATION, enrich_application, validate_question
from question_patterns import validate_coverage

ROOT=Path(__file__).resolve().parents[1]
EXTRA={}
def topic(id,signal,approach,trap,rows):
    EXTRA[id]=dict(signal=signal,approach=approach,trap=trap,rows=rows)

# Iedere regel: vraag, opties, juiste index, tussenstappen, herkenningspatroon, valkuil.
# Eerst een toepassingsvraag (niveau 2), daarna twee combinaties/afwegingen (niveau 3).
topic('beginnen','Er wordt een uitspraak gevraagd over meer posten dan je onderzoekt.','Benoem populatie, steekproef en de gevraagde grootheid vóór je rekent.','Een grote steekproef maakt een selectief gekozen steekproef niet representatief.',[
 ('Van 4.000 facturen zijn er 100 willekeurig gekozen. Hun gemiddelde is € 70. Welk bedrag is de directe schatting van het populatietotaal?', ['€ 7.000','€ 280.000','€ 70','€ 400.000'],1,['Het steekproefgemiddelde is 70; de populatieomvang N is 4.000.','Schat het totaal met N × gemiddelde = 4.000 × 70 = 280.000.'],'Een totaal voor de hele populatie gevraagd? Vermenigvuldig het gemiddelde met N.','100 × 70 is alleen het steekproeftotaal.'),
 ('Je kiest de 1.000 goedkoopste facturen uit 10.000 facturen. Wat is de sterkste kritiek op een schatting voor alle facturen?', ['1.000 waarnemingen zijn altijd te weinig','De selectie kan systematisch afwijken van de populatie','Er ontbreekt alleen een afronding','Een betrouwbaarheidsinterval herstelt de selectiefout'],1,['De selectie hangt samen met de factuurwaarde.','Meer waarnemingen of een interval nemen die selectiviteit niet weg.'],'De selectie hangt af van het kenmerk dat je wilt schatten: beoordeel eerst het steekproefontwerp.','Groot n is geen vervanging voor een geschikte selectie.'),
 ('Een berekening levert Ŵ = € 240.000 en een standaardfout van € 5.000. Met gegeven t = 2: welke uitspraak is volledig?', ['W is exact € 240.000','De populatie bevat 5.000 posten','De schatting is € 240.000 met interval [€ 230.000; € 250.000]','95% van de afzonderlijke posten ligt tussen deze grenzen'],2,['De marge is 2 × 5.000 = 10.000.','Het interval rond het totale W is 240.000 ± 10.000.'],'Schatting én onzekerheid gegeven: combineer ze, en benoem waarop het interval betrekking heeft.','Een interval voor een totaal is geen interval voor individuele posten.')])
topic('rekenen','Je krijgt een som, som van kwadraten of een spreidingsmaat.','Houd Σw², (Σw)², s², s en de standaardfout uit elkaar.','Een variantie staat in gekwadrateerde eenheden.',[
 ('Voor de waarden 2, 4 en 6 is de steekproefvariantie s² gelijk aan:', ['4','8/3','8','2'],0,['Het gemiddelde is 4. De gekwadrateerde afwijkingen zijn 4, 0 en 4.','Deel 8 door n − 1 = 2: s² = 4.'],'Een steekproefvariantie met geschat gemiddelde: deel door n − 1.','De wortel, 2, is s en niet s².'),
 ('n = 4, Σw = 20 en Σw² = 120. Wat is de standaardafwijking s, afgerond op twee decimalen?', ['6,67','2,24','2,58','10,95'],2,['s² = [120 − 20²/4]/3 = 20/3.','s = √(20/3) ≈ 2,58.'],'Totalen in plaats van losse waarden: gebruik de rekenvorm met Σw² en (Σw)².','6,67 is de variantie; neem nog de wortel.'),
 ('s = 12 en n = 36. Negeer de eindigheidscorrectie. Welke combinatie klopt?', ['Spreiding posten 2; standaardfout gemiddelde 12','Spreiding posten 12; standaardfout gemiddelde 2','Beide zijn 12','Beide zijn 144'],1,['s beschrijft de spreiding van individuele posten.','De standaardfout van het gemiddelde is 12/√36 = 2.'],'Hetzelfde gegevensbestand kan zowel individuele spreiding als schattingsonzekerheid hebben.','De standaardfout vervangen door s maakt de intervalmarge te groot.')])
topic('onzekerheid','De vraag noemt betrouwbaarheid, een- of tweezijdigheid, breedte of een tabelrij.','Zet betrouwbaarheid om in α, kies de juiste staart en gebruik de gegeven vrijheidsgraden.','De halve breedte E is iets anders dan de totale breedte 2E.',[
 ('Een tweezijdig 95%-interval heeft per staart welke overschrijdingskans?', ['0,95','0,05','0,025','0,475'],2,['α = 1 − 0,95 = 0,05.','Verdeel α over twee staarten: 0,025 per staart.'],'Twee grenzen en 95% betrouwbaarheid: verdeel de resterende 5% over beide staarten.','De tweezijdige p-waarde wordt later met α vergeleken, niet met α/2.'),
 ('Ŵ = € 101.250, standaardfout = € 1.200 en t = 2. Rond het interval naar buiten af op honderden euro’s.', ['[€ 98.900; € 103.700]','[€ 98.800; € 103.700]','[€ 98.800; € 103.600]','[€ 100.000; € 102.500]'],1,['De marge is 2.400: exacte grenzen 98.850 en 103.650.','Naar buiten afronden geeft onder 98.800 en boven 103.700.'],'Er staat “naar buiten”: de ondergrens naar beneden, de bovengrens naar boven.','Gewoon afronden kan een grens naar binnen verschuiven.'),
 ('Je wilt een smallere intervalmarge, terwijl betrouwbaarheid en spreiding gelijk blijven. Welke ingreep helpt?', ['Een kleinere steekproef','Een grotere steekproef','Minder decimalen gebruiken','De totale breedte als standaardfout behandelen'],1,['De standaardfout neemt af als n toeneemt.','Bij dezelfde kritieke waarde wordt ook de marge kleiner.'],'Kleinere onzekerheid zonder de betrouwbaarheid te verlagen: denk aan meer waarnemingen.','Afronden verbetert de statistische nauwkeurigheid niet.')])
topic('mpu','Je schat een totaal met werkelijke waarden zonder correctie op een bekend boektotaal.','Gebruik Nw̄ en de spreiding s_w, inclusief de eindigheidscorrectie indien nodig.','Vermenigvuldig voor het populatietotaal met N, niet met n.',[
 ('N = 1.000, n = 100, w̄ = 80 en s_w = 20. Zonder eindigheidscorrectie is de standaardfout van het geschatte totaal:', ['2','20','200','2.000'],3,['De standaardfout van het gemiddelde is 20/√100 = 2.','Voor het totaal: N × 2 = 2.000.'],'De vraag gaat over de standaardfout van het totaal: schaal de onzekerheid van het gemiddelde met N.','2 hoort bij het gemiddelde, niet bij het totaal.'),
 ('N = 1.000, n = 100, w̄ = 80, s_w = 20, t = 2. Met eindigheidscorrectie √(900/999): welk interval volgt bij benadering?', ['[€ 79.996; € 80.004]','[€ 76.203; € 83.797]','[€ 40.000; € 120.000]','[€ 78.000; € 82.000]'],1,['Ŵ = 1.000 × 80 = 80.000.','s_MPU = 1.000 × 20/10 × √(900/999) ≈ 1.898,32.','De marge is circa 3.796,63.'],'Herken de keten totaal → standaardfout totaal → marge → grenzen.','De factor t moet ook worden toegepast.'),
 ('Alle 500 posten zijn gecontroleerd. Hun werkelijke gemiddelde is € 40. Welke uitkomst past bij MPU?', ['Totaal € 20.000; steekproefstandaardfout nul','Totaal € 40; standaardfout onbekend','Totaal € 20.000; standaardfout altijd 40','Er kan geen totaal worden bepaald'],0,['Het totaal is Nw̄ = 500 × 40 = 20.000.','Bij n = N wordt de eindigheidscorrectie nul.'],'Integrale controle: er blijft geen onzekerheid door steekproeftrekking over.','Dit zegt niet dat meet- of registratiefouten onmogelijk zijn.')])
topic('verschil','Boekwaarden en werkelijke waarden verschillen ongeveer met een vast bedrag.','Definieer e = b − w en corrigeer het bekende B met Nē.','Een negatief verschil betekent dat de werkelijke waarde hoger is.',[
 ('B = € 100.000, N = 1.000 en ē = € 4. Wat is de geschatte werkelijke waarde?', ['€ 104.000','€ 4.000','€ 96.000','€ 100.004'],2,['De totale geschatte fout is Nē = 4.000.','Ŵ_V = B − Nē = 96.000.'],'Een bekende boekwaarde en een gemiddelde fout: corrigeer B met het geschatte totale verschil.','De geschatte fout is niet het geschatte werkelijke totaal.'),
 ('B = € 10.000, N = 500 en ē = −€ 3. Wat is Ŵ_V?', ['€ 8.500','€ 11.500','−€ 1.500','€ 10.003'],1,['Nē = −1.500.','B − Nē = 10.000 − (−1.500) = 11.500.'],'Controleer eerst het teken van b − w. Een negatieve fout wordt van B afgetrokken.','Twee mintekens geven hier een verhoging van het totaal.'),
 ('B = € 10.000, N = 500, n = 50, ē = 2, s_e = 5 en t = 2. Negeer de eindigheidscorrectie. Welk interval volgt bij benadering?', ['[€ 8.293; € 9.707]','[€ 9.293; € 10.707]','[€ 8.990; € 9.010]','[€ 7.586; € 10.414]'],0,['Ŵ_V = 10.000 − 500 × 2 = 9.000.','s_V = 500 × 5/√50 ≈ 353,55.','9.000 ± 2 × 353,55 geeft circa [8.293; 9.707].'],'Gebruik de spreiding van de verschillen, niet die van de werkelijke posten.','Centreer het interval rond Ŵ_V, niet rond B.')])
topic('quotient','De werkelijke waarde is ongeveer een vast percentage van de boekwaarde.','Bereken de goedratio q = Σw/Σb en vermenigvuldig met B.','Een goedratio is geen foutratio.',[
 ('Σw = € 72.000, Σb = € 80.000 en B = € 200.000. Wat is Ŵ_Q?', ['€ 20.000','€ 180.000','€ 222.222','€ 192.000'],1,['q = 72.000/80.000 = 0,90.','Ŵ_Q = 0,90 × 200.000 = 180.000.'],'Verhouding in de steekproef toepassen op het bekende boektotaal.','20.000 is de geschatte fout; 180.000 is de werkelijke waarde.'),
 ('Boekwaarden zijn 100, 200 en 400; werkelijke waarden 90, 180 en 360. Welk patroon past het best?', ['Een vast verschil van € 10','Een vaste goedratio van 0,90','Geen verband tussen beide waarden','Een vaste goedratio van 1,10'],1,['De verhoudingen zijn steeds 0,90.','De verschillen zijn 10, 20 en 40 en dus niet constant.'],'Vergelijk procentuele afwijkingen met absolute afwijkingen om de schatter te herkennen.','Het eerste verschil van 10 geldt niet voor alle posten.'),
 ('De goedratio is 0,96 en B = € 500.000. Gevraagd wordt de totale overwaardering in de boeken. Wat antwoord je?', ['€ 480.000','€ 520.000','€ 20.000','€ 0,04'],2,['Geschatte werkelijke waarde: 0,96 × 500.000 = 480.000.','Overwaardering: B − Ŵ_Q = 20.000.'],'Lees of het gevraagde bedrag de werkelijke waarde of juist de fout is.','Een juiste formule kan alsnog het verkeerde gevraagde bedrag opleveren.')])
topic('regressieschatter','Je kent B en corrigeert de directe schatting met een lineair verband tussen b en w.','Bereken b₁ en de correctie b₁(B − Nb̄).','Een hoge correlatie bewijst niet dat alle waarden exact bekend zijn.',[
 ('R_bw = 0,8, s_w = 30 en s_b = 20. Wat is b₁?', ['0,533','1,2','0,8','24'],1,['b₁ = R_bw × s_w/s_b.','0,8 × 30/20 = 1,2.'],'De regressieschatter vraagt een helling uit correlatie en twee standaardafwijkingen.','Verwissel s_w/s_b niet met s_b/s_w.'),
 ('N = 1.000, w̄ = 90, b̄ = 100, B = 105.000 en b₁ = 0,8. Wat is Ŵ_R?', ['€ 90.000','€ 84.000','€ 94.000','€ 105.000'],2,['MPU geeft Nw̄ = 90.000.','B − Nb̄ = 105.000 − 100.000 = 5.000.','Correctie: 0,8 × 5.000 = 4.000; totaal 94.000.'],'Het bekende boektotaal wijkt af van het uit de steekproef geschatte boektotaal.','B is de hulpinformatie, niet automatisch het antwoord.'),
 ('De standaardfout van MPU is 10.000 en R_bw = 0,6. Wat is de standaardfout van de regressieschatter?', ['4.000','6.000','6.400','8.000'],3,['Correctiefactor = √(1 − 0,6²) = √0,64 = 0,8.','10.000 × 0,8 = 8.000.'],'De correlatie werkt via 1 − R² onder een wortel op de standaardfout.','1 − R en 1 − R² zijn geen standaardfoutfactoren zonder wortel.')])
topic('steekproefomvang','De opgave vraagt hoeveel controles nodig zijn voor een gewenste nauwkeurigheid.','Zet breedte om naar E, kies de variantie en rond de benodigde n omhoog.','Totale benodigde omvang en uitbreiding zijn verschillende antwoorden.',[
 ('De gewenste totale intervalbreedte is 8.000. In γ = E²/(t²Ns²) vul je voor E in:', ['16.000','8.000','4.000','2.000'],2,['De breedte van het interval is 2E.','E = 8.000/2 = 4.000.'],'“Totale breedte” moet eerst worden gehalveerd voordat je de omvangsformule gebruikt.','Een dubbele E wordt in de formule gekwadrateerd en heeft dus veel effect.'),
 ('Gebruik γ = E²/(t²Ns²) en n = N/(1 + γ). N = 1.000, E = 400, t = 2, s² = 100. Welke omvang is nodig?', ['285','286','714','715'],3,['γ = 400²/(2² × 1.000 × 100) = 0,4.','n = 1.000/1,4 ≈ 714,286.','Rond naar boven: 715.'],'De formulebladroute gebruikt eerst γ en daarna de begrensde omvang n.','Afronden op het dichtstbijzijnde gehele getal is hier niet voldoende.'),
 ('Een berekende totale omvang is 124,01. Er zijn al 80 posten gecontroleerd. Hoeveel extra controles zijn nodig?', ['44','45','124','125'],1,['Rond eerst de totale behoefte op naar 125.','De uitbreiding is 125 − 80 = 45.'],'“Extra” vraagt om een verschil na veilig afronden van de totale omvang.','125 is de totale omvang, niet de uitbreiding.')])
topic('stratificatie','De populatie bestaat uit groepen met eigen Nᵢ, nᵢ en spreiding.','Schat per stratum, tel totalen en varianties afzonderlijk op en neem daarna de wortel.','Een integraal gecontroleerd topstratum voegt een bekend totaal toe, maar geen steekproefvariantie.',[
 ('Stratum 1 heeft N₁ = 100 en gemiddelde 20; stratum 2 N₂ = 200 en gemiddelde 30. Het bekende werkelijke topstratumtotaal is 1.000. Wat is het geschatte totaal?', ['7.000','8.000','9.000','15.000'],2,['100 × 20 + 200 × 30 = 8.000.','Tel het bekende werkelijke topstratumtotaal 1.000 erbij: 9.000.'],'Verschillende groepsgemiddelden: weeg ze met hun eigen populatieomvang.','Vergeet het integraal gecontroleerde deel niet.'),
 ('Bij gelijke controlekosten: N₁ = 600, s₁ = 10, N₂ = 400, s₂ = 30 en n = 90. Wat is de Neyman-allocatie?', ['54 en 36','45 en 45','30 en 60','60 en 30'],2,['Gewichten Nᵢsᵢ zijn 6.000 en 12.000.','Verdeel 90 in de verhouding 1:2: 30 en 60.'],'Neyman houdt naast groepsgrootte ook rekening met spreiding.','54 en 36 is de evenredige allocatie, niet Neyman.'),
 ('Onafhankelijke stratumtotalen hebben standaardfouten 300 en 400. Het totale geschatte bedrag inclusief gecontroleerd topstratum is 20.000. Gebruik t = 2. Welk interval volgt?', ['[18.600; 21.400]','[19.000; 21.000]','[19.500; 20.500]','[19.300; 20.700]'],1,['Gecombineerde standaardfout = √(300² + 400²) = 500.','Marge = 2 × 500 = 1.000.','Het interval is 20.000 ± 1.000.'],'Tel varianties van onafhankelijke schattingen op, niet de standaardfouten zelf.','300 + 400 gebruiken maakt de marge onjuist.')])
topic('regressielijn','Een vergelijking verbindt x met een voorspelde waarde ŷ.','Bereken eerst de voorspelling en daarna het residu y − ŷ.','Een statistisch verband bewijst geen oorzaak.',[
 ('ŷ = 5 + 3x. Een waarneming heeft x = 4 en y = 20. Wat is het residu?', ['−3','3','17','20'],1,['Voorspelling: 5 + 3 × 4 = 17.','Residu: y − ŷ = 20 − 17 = 3.'],'Waarneming én vergelijking gegeven: twee stappen, niet direct y − x.','De voorspelling is niet het residu.'),
 ('Voor dezelfde data geeft model A residuen −2, 2 en model B residuen −3, 3. Welk model heeft volgens het OLS-criterium de kleinste fout?', ['A: SSE = 8','B: SSE = 0','Beide: som residuen is nul','B: SSE = 6'],0,['A: 4 + 4 = 8. B: 9 + 9 = 18.','OLS vergelijkt de som van gekwadrateerde residuen.'],'Twee modellen vergelijken op residuen: kwadrateer eerst zodat plus en min niet wegvallen.','Een som van nul kan grote positieve en negatieve fouten verbergen.'),
 ('Er is een sterk positief verband tussen leeftijd en salaris. Welke conclusie is op basis daarvan verdedigbaar?', ['Een extra jaar leeftijd veroorzaakt altijd dezelfde salarisstijging','Iedere oudere persoon verdient meer','Binnen de onderzochte data hangen leeftijd en salaris positief samen','Andere verklarende variabelen zijn overbodig'],2,['Correlatie beschrijft samenhang binnen de data.','Causaliteit en uitspraken over iedere persoon volgen daar niet automatisch uit.'],'Woorden zoals “veroorzaakt” of “iedereen” gaan verder dan een gemeten verband.','Een sterk verband sluit andere verklaringen niet uit.')])
topic('anova','SPSS geeft SS, df, MS, F en R².','Splits totale variatie in verklaarde en resterende variatie; deel SS door de juiste df.','R² is een aandeel van de variatie, niet van de standaardafwijking.',[
 ('TotalSS = 200 en SSR = 150. Welke combinatie klopt?', ['SSE = 50; R² = 0,75','SSE = 350; R² = 0,25','SSE = 50; R² = 0,25','SSE = 150; R² = 0,75'],0,['SSE = TotalSS − SSR = 50.','R² = SSR/TotalSS = 150/200 = 0,75.'],'Ontbrekende ANOVA-waarden: begin met de identiteit TotalSS = SSR + SSE.','1 − R² is de onverklaarde fractie.'),
 ('n = 20, k = 2, SSR = 180 en SSE = 34. Wat is de globale F?', ['90','5,29','45','2'],2,['MSR = SSR/k = 90.','Residual df = 20 − 2 − 1 = 17; MSE = 34/17 = 2.','F = MSR/MSE = 45.'],'Voor F moeten beide kwadratensommen eerst door hun vrijheidsgraden.','SSR/SSE is niet de globale F.'),
 ('R² = 0,81 en MSE = 25 voor een model van salaris. Wat is een juiste interpretatie?', ['81% van alle salarissen wordt exact voorspeld','Het model verklaart 81% van de variatie; de residuele standaardafwijking is 5','De correlatie is zeker +0,81','De residuele standaardafwijking is 25'],1,['R² meet de verklaarde fractie van de variatie.','De residuele standaardafwijking is √MSE = 5.'],'Koppel elke uitvoermaat aan haar eigen betekenis en eenheid.','Een hoge R² betekent geen foutloze individuele voorspellingen.')])
topic('toetsen','De vraag wil bewijs voor een verband, richting of extra bijdrage.','Bepaal H₀/H₁ en een- of tweezijdigheid, bereken de toets en concludeer in de casus.','Bij een tweezijdige p-waarde vergelijk je met α, niet met α/2.',[
 ('B = 6 en Std. Error = 2. Wat is t voor H₀: β = 0?', ['12','0,333','3','4'],2,['t = (B − 0)/Std. Error.','6/2 = 3.'],'Een coëfficiënt met zijn standaardfout: gebruik de t-toets uit Coefficients.','B × standaardfout is geen toetsingsgrootheid.'),
 ('H₁: β > 0, maar de gevonden helling is negatief. De tweezijdige p is 0,02. Wat betekent dit voor de gevraagde stijging bij α = 0,05?', ['Significant stijgend, want 0,02/2 < 0,05','Geen bewijs voor de gevraagde stijging','β is bewezen nul','Elke kleine tweezijdige p bewijst een stijging'],1,['Het gevonden effect ligt tegengesteld aan H₁.','Je mag de tweezijdige p niet zonder controle van de richting halveren om een stijging te claimen.'],'Bij een eenzijdige toets moet het teken aansluiten op de alternatieve hypothese.','Een klein p-getal vertelt op zichzelf niet welke richting wordt ondersteund.'),
 ('Een globale F-toets is significant bij een model met drie voorspellers. Twee individuele t-toetsen zijn niet significant. Is dit per definitie tegenstrijdig?', ['Ja, alle drie moeten significant zijn','Nee, de F-toets toetst de gezamenlijke nulhypothese','Ja, een F-toets toetst normaliteit','Nee, want t-toetsen gebruiken geen hypothesen'],1,['F toetst of alle hellingscoëfficiënten gezamenlijk nul zijn.','De individuele t-toetsen beoordelen afzonderlijke bijdragen gegeven de overige voorspellers.'],'Een globale conclusie en een conclusie over één variabele hebben verschillende nulhypothesen.','“Het model is significant” betekent niet “elke variabele is significant”.')])
topic('diagnostiek','Een grafiek of tabel gaat over residuen, afwijkende x-waarden of invloed.','Benoem het signaal, de aanname en de consequentie; geef een remedie als gevraagd.','Een afwijkend punt mag je niet automatisch verwijderen.',[
 ('Een residuplot toont bij hogere voorspelde waarden een steeds bredere wolk. Welk probleem wordt gesuggereerd?', ['Multicollineariteit','Heteroscedasticiteit','Een bewezen causale relatie','Een exact lineair model'],1,['Een trechter betekent veranderende spreiding van de residuen.','Dat is heteroscedasticiteit: niet-constante foutvariantie.'],'Let in een residuplot op breedte van de wolk, niet alleen op de middenlijn.','Multicollineariteit gaat over overlap tussen voorspellers.'),
 ('Shapiro-Wilk heeft p = 0,40 bij α = 0,05. Welke formulering is het zorgvuldigst?', ['De residuen zijn bewezen normaal','Normaliteit wordt niet verworpen op basis van deze toets','Het model verklaart 40% van de variatie','Alle uitschieters zijn uitgesloten'],1,['0,40 > 0,05: H₀ wordt niet verworpen.','Dat levert geen bewijs dat de verdeling exact normaal is.'],'Een niet-significante toets vraagt om “niet verwerpen”, niet om “bewijzen”.','Normaliteit, uitschieters en verklaarde variatie zijn verschillende vragen.'),
 ('Een punt heeft een grote Cook’s Distance. Wat is de beste vervolgstap?', ['Altijd verwijderen','Onderzoeken of het punt klopt en hoeveel invloed het op de schatting heeft','De waarde van y vervangen door het gemiddelde','Concluderen dat de residuen normaal zijn'],1,['Cook’s Distance signaleert mogelijke invloed op de geschatte regressie.','Controleer de waarneming en beoordeel het model met inhoudelijke onderbouwing.'],'Invloedrijk is een reden voor onderzoek, geen automatische datacorrectie.','Verwijderen zonder inhoudelijke reden kan de analyse vertekenen.')])
topic('voorspellen','Er wordt een nieuwe y of een interval bij een bepaalde x₀ gevraagd.','Onderscheid de gemiddelde respons van één nieuwe waarneming en controleer het x-bereik.','Een individuele voorspelling heeft ook nieuwe individuele storing.',[
 ('Een model is geschat voor leeftijden 20 tot 60. Voorspellen voor een 80-jarige is:', ['Interpolatie','Extrapolatie','Stratificatie','Een gegarandeerd nauwkeurige voorspelling'],1,['80 ligt buiten het waargenomen bereik 20 tot 60.','Dit heet extrapolatie; het verband hoeft buiten dat bereik niet hetzelfde te blijven.'],'Vergelijk x₀ met het bereik van de data vóór je de formule invult.','De vergelijking kunnen invullen is niet hetzelfde als een verantwoorde voorspelling.'),
 ('Voor één nieuwe waarneming bij x₀ = x̄: ŷ = 50, n = 25, s_e = 5 en t = 2. Gebruik ŷ ± t s_e √(1 + 1/n). Welk interval volgt ongeveer?', ['[48; 52]','[40; 60]','[39,80; 60,20]','[45; 55]'],2,['√(1 + 1/25) = √1,04.','De marge is 2 × 5 × √1,04 ≈ 10,198.','Dus ongeveer [39,80; 60,20].'],'De extra 1 onder de wortel hoort bij één nieuwe waarneming.','Die 1 weglaten geeft het veel smallere interval voor de gemiddelde respons.'),
 ('Bij hetzelfde model verschuift x₀ van x̄ naar een veel verder gelegen waarde. Alle andere gegevens blijven gelijk. Wat gebeurt doorgaans met het voorspellingsinterval?', ['Het wordt smaller','Het wordt breder','Het houdt altijd dezelfde breedte','De betrouwbaarheid wordt vanzelf 100%'],1,['De term (x₀ − x̄)² wordt groter.','Die extra term vergroot de standaardfout van de voorspelling.'],'Afstand tot het centrum van de x-data vergroot de onzekerheid.','Een puntschatting buiten het centrum kan wel berekenbaar zijn, maar is onzekerder.')])
topic('meervoudig','De vergelijking bevat meerdere verklarende variabelen of dummy’s.','Vul alle variabelen in en interpreteer een coëfficiënt bij gelijkblijvende overige variabelen.','Een dummycoëfficiënt is een verschil ten opzichte van de referentiegroep.',[
 ('ŷ = 1.000 + 50x + 200D, met D = 1 voor groep B. Wat is ŷ bij x = 4 en groep B?', ['1.200','1.250','1.400','5.200'],2,['Vul x = 4 en D = 1 in.','1.000 + 50 × 4 + 200 = 1.400.'],'Een groepsindicator van 1 voegt het dummy-effect toe aan de overige termen.','De constante wordt één keer meegenomen.'),
 ('ŷ = 1.000 + 50x + 200D. Persoon A heeft x = 6, D = 0; persoon B x = 4, D = 1. Hoeveel hoger is de voorspelling van B?', ['200','100','300','−100'],1,['A: 1.000 + 300 = 1.300. B: 1.000 + 200 + 200 = 1.400.','Verschil B − A = 100.'],'De personen verschillen op twee kenmerken: verwerk beide verschillen.','Alleen het dummy-effect 200 nemen negeert het verschil in x.'),
 ('Model A en B gebruiken dezelfde y en waarnemingen. B heeft meer voorspellers: R² stijgt van 0,70 naar 0,71, adjusted R² daalt van 0,68 naar 0,67. Welke afweging is passend?', ['B is zeker beter doordat R² hoger is','De extra complexiteit verbetert de gecorrigeerde modelkwaliteit hier niet','A is zeker causaal','De tabel kan niet kloppen'],1,['Gewone R² kan toenemen door extra voorspellers.','Adjusted R² corrigeert voor de modelomvang en daalt hier.'],'Vergelijk bij verschillende aantallen voorspellers ook een maat die complexiteit meeweegt.','Alleen op de grootste R² selecteren bevoordeelt grotere modellen.')])
topic('transformaties','De uitvoer noemt logarithmic, exponential, power of ln.','Lees welke variabele is getransformeerd en keer de bewerking zo nodig terug.','Een voorspelling op logschaal is nog geen bedrag op de oorspronkelijke schaal.',[
 ('Het logaritmische model is ŷ = 10 + 2 ln(x). Voor x = e geldt:', ['ŷ = 10','ŷ = 12','ŷ = exp(12)','ŷ = 2'],1,['ln(e) = 1.','ŷ = 10 + 2 × 1 = 12.'],'Alleen x is gelogaritmeerd; y staat al op de oorspronkelijke schaal.','Je hoeft hier niet nog exp op de uitkomst toe te passen.'),
 ('ln(ŷ) = 1 + 0,5x. Wat is de teruggetransformeerde puntschatting bij x = 2?', ['2','ln(2)','exp(2) ≈ 7,389','exp(1) + exp(1) ≈ 5,437'],2,['Eerst op logschaal: 1 + 0,5 × 2 = 2.','Keer ln om: exp(2) ≈ 7,389.'],'Een gelogaritmeerde y moet na invullen worden teruggetransformeerd.','exp(a + b) is niet gelijk aan exp(a) + exp(b).'),
 ('Voor een machtsmodel geldt ŷ = 3x². Met welke factor verandert ŷ als x verdubbelt?', ['2','3','4','6'],2,['Bij 2x wordt de voorspelling 3(2x)² = 12x².','Verhouding tot 3x² is 4.'],'Bij een machtsverband werkt een vermenigvuldiging van x door via de exponent.','Verdubbelen van x betekent niet automatisch verdubbelen van y.')])
topic('modelbouw','De vraag vergelijkt modellen, selectieprocedures of overlap tussen voorspellers.','Controleer vergelijkbaarheid, VIF/tolerance en de bijdrage van toegevoegde variabelen.','Multicollineariteit gaat over x-variabelen onderling, niet alleen over x met y.',[
 ('Tolerance = 0,08. Welke combinatie klopt volgens de cursusgrens VIF > 10?', ['VIF = 0,92; geen signaal','VIF = 12,5; probleemsignaal','VIF = 8; probleemsignaal','VIF = 0,08; probleemsignaal'],1,['VIF = 1/0,08 = 12,5.','Dit ligt boven de cursusgrens van 10.'],'Tolerance en VIF zijn elkaars omgekeerde; pas daarna de grens toe.','Een laag tolerancegetal is geen laag VIF-getal.'),
 ('Twee geneste modellen gebruiken dezelfde data en y. Eén variabele wordt toegevoegd: SSR klein = 800, SSR groot = 850, MSE groot = 10. De kritieke F is 4. Wat volgt?', ['F = 5; de extra bijdrage is significant','F = 50; niet significant','F = 0,2; significant','Een hoge R² bewijst normaliteit'],0,['Voor één extra variabele: F = (850 − 800)/10 = 5.','5 > 4, dus de extra bijdrage is significant op het gebruikte toetsniveau.'],'Één extra variabele in geneste modellen: vergelijk de extra verklaarde variatie met de resterende fout.','Zonder dezelfde waarnemingen en dezelfde y is deze vergelijking niet geldig.'),
 ('Bij backward-selectie verdwijnt één variabele. Wat doe je vóór een volgende verwijderbeslissing?', ['De oude p-waarden blijven gebruiken','Het model opnieuw schatten en de nieuwe p-waarden beoordelen','Alle gecorreleerde variabelen verwijderen','De grootste B altijd verwijderen'],1,['De geschatte bijdragen hangen af van de andere opgenomen voorspellers.','Na verwijderen kunnen coëfficiënten en p-waarden veranderen.'],'Stapsgewijze selectie betekent na iedere stap opnieuw evalueren.','De grootte van B hangt ook af van de meeteenheid en is geen verwijdercriterium op zichzelf.')])
topic('validatie','Je beoordeelt voorspellingen op gegevens die niet voor het schatten zijn gebruikt.','Bereken kwadratische voorspelfouten op de testset en onderscheid die van trainingsfouten.','De testset is geen onafhankelijke eindcontrole meer als je haar steeds gebruikt voor modelkeuze.',[
 ('Testwaarden y zijn 10, 14, 20; voorspellingen zijn 12, 13, 17. Wat is MSPR?', ['2','14','14/3 ≈ 4,67','7'],2,['Fouten zijn −2, 1, 3; kwadraten 4, 1, 9.','MSPR = (4 + 1 + 9)/3 = 14/3.'],'Testfouten: kwadrateer en deel door het aantal testwaarnemingen.','Hier deel je niet door n − k − 1.'),
 ('Trainings-MSE = 4 en MSPR op een ongebruikte testset = 25. Wat is de belangrijkste aanwijzing?', ['Het model voorspelt op nieuwe data veel slechter dan de training suggereert','De testset bevat zeker fraude','R² moet negatief zijn','MSPR moet door 4 worden gedeeld om geldig te worden'],0,['MSPR ligt veel hoger dan de trainings-MSE.','Onderzoek waarom de voorspelling op ongebruikte data slechter is.'],'Vergelijk prestaties buiten de trainingsset om generalisatie te beoordelen.','Dit patroon geeft een signaal, maar bewijst geen unieke oorzaak.'),
 ('Je kiest uit twintig modellen steeds het model met de laagste fout op dezelfde testset. Is die set daarna nog een onafhankelijke eindcontrole?', ['Ja, omdat hij testset heet','Nee, de modelkeuze is inmiddels afgestemd op deze set','Ja, zolang er geen intercept is','Alleen als MSPR nul is'],1,['De testresultaten zijn gebruikt om het model te selecteren.','Daardoor is de uiteindelijke prestatie op die set geen onafhankelijke evaluatie meer.'],'Kijk hoe de data feitelijk zijn gebruikt, niet alleen hoe de set heet.','Herhaald kiezen op dezelfde testset kan een te gunstig beeld geven.')])
topic('tentamen','Een open vraag combineert gegevens, methode, berekening en conclusie.','Onderstreep eerst het gevraagde resultaat en plan de stappen die daarvoor nodig zijn.','Een losse uitkomst zonder methode of casusconclusie kan onvoldoende zijn.',[
 ('De vraag luidt: “Beoordeel normaliteit en motiveer met de uitvoer.” Welk antwoord sluit het best aan?', ['Alleen: nee','Alleen: R² = 0,80','Noem de normaliteitstoets, p ten opzichte van α en de conclusie over residuen','Bereken altijd de steekproefomvang'],2,['Bepaal welke aanname wordt getoetst.','Verwijs naar de juiste uitvoer en verbind de p-waarde met je conclusie.'],'Het werkwoord “motiveer” vraagt om controleerbare ondersteuning uit de bron.','R² is geen normaliteitstoets.'),
 ('Je berekent correct een totale benodigde n van 521. Er zijn al 180 controles uitgevoerd. De vraag vraagt de uitbreiding. Wat is een volledig antwoord?', ['521 controles','341 extra controles; totaal 521','180 extra controles','701 controles'],1,['De totale behoefte is 521.','Er zijn al 180 gedaan, dus 521 − 180 = 341 extra.'],'Lees aan het einde opnieuw welk aantal wordt gevraagd.','Een juiste tussenuitkomst kan nog steeds niet het gevraagde eindantwoord zijn.'),
 ('Een vraag geeft een interval en vraagt of een opvallende realisatie fraude bewijst. Welke redenering is passend?', ['Buiten het interval bewijst fraude','Binnen het interval sluit fraude uit','Een afwijking kan aanleiding zijn voor onderzoek, maar het interval bewijst geen oorzaak','De realisatie moet altijd vervangen worden'],2,['Een interval beschrijft statistische onzekerheid onder modelaannames.','Een afwijking verklaart niet waarom de waarneming afwijkt.'],'Onderscheid statistisch signaal, inhoudelijk oordeel en bewijs van een oorzaak.','Een statistische grens is geen automatische fraudebeslissing.')])

def make_topics():
    """Stel de vraagdata samen zonder gedeelde browserbestanden te schrijven."""
    topics=[]
    expected = {f'{key}-{i+1}' for key, meta in EXTRA.items() for i in range(len(meta['rows']))}
    if set(APPLICATION) != expected:
        raise ValueError(f'Toepassingsuitleg ontbreekt of is verouderd: {set(APPLICATION) ^ expected}')
    for lesson in C.lessons:
        meta=EXTRA[lesson['id']]
        levels=[1,1,2]
        if lesson['id']=='stratificatie': levels=[1,2,1]
        if lesson['id']=='meervoudig': levels=[2,1,1]
        questions=[]
        for i,old in enumerate(lesson['questions']):
            question=dict(old,id=f"mc-{lesson['id']}-basis-{i+1}",level=levels[i])
            # Correcte terminologie: geen steekproefonzekerheid is iets anders dan geen spreiding in posten.
            if lesson['id']=='stratificatie' and i==2:
                question['prompt']='Wat is de steekproefvariantie van het geschatte totaal van een integraal gecontroleerd topstratum?'
            questions.append(question)
        for i,(prompt,options,correct,steps,pattern,trap) in enumerate(meta['rows']):
            question=dict(id=f"mc-{lesson['id']}-toepassing-{i+1}",prompt=prompt,options=options,correct=correct,level=2 if i==0 else 3,steps=steps,explanation=' '.join(steps),pattern=pattern,trap=trap)
            questions.append(enrich_application(question, lesson['id'], i+1, lesson['refs']))
        questions.sort(key=lambda q:q['level'])
        # Eerst de oorspronkelijke zes posities behouden voor stabiele antwoordrotatie.
        from completion_questions import for_lesson
        questions.extend(for_lesson(lesson))
        # Vaste antwoordvolgorde per vraag; de juiste letter verraadt het niveau niet.
        for i,q in enumerate(questions):
            target=(len(topics)+i)%len(q['options'])
            shift=(q['correct']-target)%len(q['options'])
            q['options']=q['options'][shift:]+q['options'][:shift]
            q['optionExplanations']=q['optionExplanations'][shift:]+q['optionExplanations'][:shift]
            q['correct']=target
            validate_question(q)
        questions.sort(key=lambda q:q['level'])
        topics.append(dict(id=lesson['id'],title=lesson['title'],phase=lesson['phase'],lesson=lesson['id'],signal=meta['signal'],approach=meta['approach'],refs=lesson['refs'],questions=questions))
    assert len(topics)==19 and sum(len(t['questions']) for t in topics)==134
    validate_coverage([q for topic in topics for q in topic['questions']])
    assert all([q['level'] for q in t['questions']]==sorted(q['level'] for q in t['questions']) for t in topics)
    return topics


def build():
    topics=make_topics()
    (ROOT/'data/mc.js').write_text('/* Gemaakt met Codex. Eigen oefenvarianten op de aangeleverde SRA-lesstof. */\nwindow.SRAMCData = '+json.dumps(dict(version=2,topics=topics),ensure_ascii=False,indent=2)+';\n',encoding='utf8')
    print('MC: 19 onderwerpen, 134 vragen, inclusief 20 brongebonden aanvullingen.')

if __name__=='__main__': build()
